[rospy.client][INFO] 2016-01-25 09:14:52,622: init_node, name[/log], pid[11282]
[xmlrpc][INFO] 2016-01-25 09:14:52,629: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 09:14:52,630: ROS Slave URI: [http://10.0.0.11:53753/]
[xmlrpc][INFO] 2016-01-25 09:14:52,630: Started XML-RPC server [http://10.0.0.11:53753/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:14:52,630: _ready: http://10.0.0.11:53753/
[rospy.registration][INFO] 2016-01-25 09:14:52,658: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-25 09:14:52,658: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[xmlrpc][INFO] 2016-01-25 09:14:52,659: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:14:52,672: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,674: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,680: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,691: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,700: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,716: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,723: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,732: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,744: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,760: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,766: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,768: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,770: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,773: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,789: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:14:52,815: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.internal][INFO] 2016-01-25 09:14:52,865: topic[/time_response] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:14:52,874: topic[/time_writing] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:14:52,883: topic[/user_feedback] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:14:52,887: topic[/clear_screen] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:14:52,892: topic[/words_to_write] adding connection to [http://10.0.0.3:45907/], count 0
[rospy.init][INFO] 2016-01-25 09:14:52,931: registered with master
[rospy.rosout][INFO] 2016-01-25 09:14:52,931: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:14:52,948: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:14:52,971: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 09:14:53,171: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:14:53,885: topic[/activity] adding connection to [http://10.0.0.11:43925/], count 0
[rospy.internal][ERROR] 2016-01-25 09:14:55,923: Unable to initiate TCP/IP socket to 10.0.0.11:44961 (http://10.0.0.11:43925/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:14:56,926: Unknown error initiating TCP/IP socket to 10.0.0.11:44961 (http://10.0.0.11:43925/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:14:56,927: topic[/activity] removing connection to http://10.0.0.11:43925/
[rospy.internal][INFO] 2016-01-25 09:15:16,798: topic[/stop_learning] adding connection to [http://10.0.0.11:50895/], count 0
[rospy.internal][WARNING] 2016-01-25 09:15:19,761: Unknown error initiating TCP/IP socket to 10.0.0.11:58637 (http://10.0.0.11:50895/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 09:15:19,761: topic[/stop_learning] removing connection to http://10.0.0.11:50895/
[rospy.core][INFO] 2016-01-25 09:15:20,422: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:15:20,437: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:15:20,439: topic[/words_to_write] removing connection to http://10.0.0.3:45907/
[rospy.internal][INFO] 2016-01-25 09:15:20,439: topic[/clear_screen] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:15:20,440: topic[/user_feedback] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:15:20,440: topic[/time_writing] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:15:20,440: topic[/time_response] removing connection to http://10.0.0.3:34103/
[rospy.impl.masterslave][INFO] 2016-01-25 09:15:20,441: signal-2
[rospy.internal][WARNING] 2016-01-25 09:15:20,500: Unknown error initiating TCP/IP socket to 10.0.0.3:36940 (http://10.0.0.3:34103/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2016-01-25 09:15:20,500: Unknown error initiating TCP/IP socket to 10.0.0.3:36940 (http://10.0.0.3:34103/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2016-01-25 09:15:20,573: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 09:15:44,161: init_node, name[/log], pid[12011]
[xmlrpc][INFO] 2016-01-25 09:15:44,175: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 09:15:44,176: ROS Slave URI: [http://10.0.0.11:55165/]
[xmlrpc][INFO] 2016-01-25 09:15:44,176: Started XML-RPC server [http://10.0.0.11:55165/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:15:44,176: _ready: http://10.0.0.11:55165/
[rospy.registration][INFO] 2016-01-25 09:15:44,187: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-25 09:15:44,187: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:15:44,187: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,203: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,221: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,269: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,283: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,305: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,333: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,343: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,353: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,362: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,374: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,382: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,389: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,399: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,406: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,413: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-25 09:15:44,419: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-25 09:15:44,476: registered with master
[rospy.rosout][INFO] 2016-01-25 09:15:44,476: initializing /rosout core topic
[rospy.internal][INFO] 2016-01-25 09:15:44,486: topic[/time_response] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:44,493: topic[/time_writing] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:44,495: topic[/words_to_write] adding connection to [http://10.0.0.3:45907/], count 0
[rospy.rosout][INFO] 2016-01-25 09:15:44,496: connected to core topic /rosout
[rospy.internal][INFO] 2016-01-25 09:15:44,499: topic[/user_feedback] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:44,500: topic[/clear_screen] adding connection to [http://10.0.0.3:34103/], count 0
[rospy.simtime][INFO] 2016-01-25 09:15:44,526: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 09:15:44,767: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:15:45,392: topic[/activity] adding connection to [http://10.0.0.11:35275/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:46,109: topic[/activity] adding connection to [http://10.0.0.11:56874/], count 1
[rospy.internal][INFO] 2016-01-25 09:15:46,127: topic[/clear_screen] adding connection to [http://10.0.0.11:56874/], count 1
[rospy.internal][INFO] 2016-01-25 09:15:46,130: topic[/clear_screen] adding connection to [http://10.0.0.11:49819/], count 2
[rospy.internal][INFO] 2016-01-25 09:15:46,130: topic[/current_score] adding connection to [http://10.0.0.11:49819/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:46,131: topic[/current_learn] adding connection to [http://10.0.0.11:49819/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:46,141: topic[/current_demo] adding connection to [http://10.0.0.11:49819/], count 0
[rospy.internal][INFO] 2016-01-25 09:15:46,142: topic[/nb_repetitions] adding connection to [http://10.0.0.11:49819/], count 0
[rospy.internal][INFO] 2016-01-25 09:18:16,754: topic[/words_to_write] adding connection to [http://10.0.0.11:33147/], count 1
[rospy.internal][ERROR] 2016-01-25 09:18:19,723: Unable to initiate TCP/IP socket to 10.0.0.11:54357 (http://10.0.0.11:33147/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:18:20,723: Unknown error initiating TCP/IP socket to 10.0.0.11:54357 (http://10.0.0.11:33147/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:18:20,723: topic[/words_to_write] removing connection to http://10.0.0.11:33147/
[rospy.internal][INFO] 2016-01-25 09:26:43,124: topic[/words_to_write] adding connection to [http://10.0.0.11:42183/], count 1
[rospy.internal][WARNING] 2016-01-25 09:26:46,115: Unknown error initiating TCP/IP socket to 10.0.0.11:33641 (http://10.0.0.11:42183/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 09:26:46,115: topic[/words_to_write] removing connection to http://10.0.0.11:42183/
[rospy.internal][INFO] 2016-01-25 09:29:58,601: topic[/stop_learning] adding connection to [http://10.0.0.11:37991/], count 0
[rospy.internal][ERROR] 2016-01-25 09:29:59,713: Unable to initiate TCP/IP socket to 10.0.0.11:41391 (http://10.0.0.11:56874/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:29:59,717: Unknown error initiating TCP/IP socket to 10.0.0.11:41391 (http://10.0.0.11:56874/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 09:29:59,717: topic[/activity] removing connection to http://10.0.0.11:56874/
[rospy.internal][ERROR] 2016-01-25 09:30:00,140: Unable to initiate TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-25 09:30:00,140: Unable to initiate TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-25 09:30:00,140: Unable to initiate TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:30:00,335: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 09:30:00,335: topic[/current_learn] removing connection to http://10.0.0.11:49819/
[rospy.internal][WARNING] 2016-01-25 09:30:00,336: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 09:30:00,336: topic[/current_demo] removing connection to http://10.0.0.11:49819/
[rospy.internal][WARNING] 2016-01-25 09:30:00,713: Unknown error initiating TCP/IP socket to 10.0.0.11:41391 (http://10.0.0.11:56874/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:00,714: topic[/clear_screen] removing connection to http://10.0.0.11:56874/
[rospy.internal][WARNING] 2016-01-25 09:30:01,141: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:01,141: topic[/clear_screen] removing connection to http://10.0.0.11:49819/
[rospy.internal][WARNING] 2016-01-25 09:30:01,142: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:01,142: topic[/current_score] removing connection to http://10.0.0.11:49819/
[rospy.internal][WARNING] 2016-01-25 09:30:01,142: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:01,142: topic[/nb_repetitions] removing connection to http://10.0.0.11:49819/
[rospy.internal][ERROR] 2016-01-25 09:30:01,521: Unable to initiate TCP/IP socket to 10.0.0.11:35629 (http://10.0.0.11:37991/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:30:02,521: Unknown error initiating TCP/IP socket to 10.0.0.11:35629 (http://10.0.0.11:37991/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:02,522: topic[/stop_learning] removing connection to http://10.0.0.11:37991/
[rospy.internal][ERROR] 2016-01-25 09:30:04,261: Unable to initiate TCP/IP socket to 10.0.0.11:56060 (http://10.0.0.11:35275/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:30:05,262: Unknown error initiating TCP/IP socket to 10.0.0.11:56060 (http://10.0.0.11:35275/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:05,262: topic[/activity] removing connection to http://10.0.0.11:35275/
[rospy.core][INFO] 2016-01-25 09:31:22,233: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:31:22,242: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:31:22,242: topic[/words_to_write] removing connection to http://10.0.0.3:45907/
[rospy.topics][ERROR] 2016-01-25 09:31:22,245: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2016-01-25 09:31:22,245: topic[/clear_screen] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:31:22,245: topic[/user_feedback] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:31:22,245: topic[/time_writing] removing connection to http://10.0.0.3:34103/
[rospy.internal][INFO] 2016-01-25 09:31:22,246: topic[/time_response] removing connection to http://10.0.0.3:34103/
[rospy.impl.masterslave][INFO] 2016-01-25 09:31:22,246: signal-2
[rospy.internal][WARNING] 2016-01-25 09:31:22,342: Unknown error initiating TCP/IP socket to 10.0.0.3:40819 (http://10.0.0.3:45907/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-01-25 09:31:22,378: signal_shutdown [atexit]
