[rospy.client][INFO] 2016-01-25 09:14:20,031: init_node, name[/withmeness], pid[10974]
[xmlrpc][INFO] 2016-01-25 09:14:20,031: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 09:14:20,032: ROS Slave URI: [http://10.0.0.11:45904/]
[xmlrpc][INFO] 2016-01-25 09:14:20,032: Started XML-RPC server [http://10.0.0.11:45904/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:14:20,032: _ready: http://10.0.0.11:45904/
[rospy.registration][INFO] 2016-01-25 09:14:20,042: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-25 09:14:20,042: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:14:20,042: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-25 09:14:20,097: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-25 09:14:20,132: registered with master
[rospy.rosout][INFO] 2016-01-25 09:14:20,132: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:14:20,134: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:14:20,135: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 09:14:20,159: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:32917/], count 0
[rospy.internal][INFO] 2016-01-25 09:14:20,382: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:15:46,102: topic[/state_activity] adding connection to [http://10.0.0.11:49819/], count 0
[rospy.internal][ERROR] 2016-01-25 09:30:00,140: Unable to initiate TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:30:01,141: Unknown error initiating TCP/IP socket to 10.0.0.11:57858 (http://10.0.0.11:49819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:30:01,141: topic[/state_activity] removing connection to http://10.0.0.11:49819/
[rospy.core][INFO] 2016-01-25 09:31:14,754: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:31:14,789: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-25 09:31:14,790: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:31:14,790: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:32917/
[rospy.impl.masterslave][INFO] 2016-01-25 09:31:14,790: signal-2
[rospy.core][INFO] 2016-01-25 09:31:29,841: signal_shutdown [signal-15]
