[rospy.client][INFO] 2016-01-25 09:40:57,256: init_node, name[/nao_writer], pid[7998]
[xmlrpc][INFO] 2016-01-25 09:40:57,257: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 09:40:57,257: ROS Slave URI: [http://10.0.0.11:39517/]
[xmlrpc][INFO] 2016-01-25 09:40:57,257: Started XML-RPC server [http://10.0.0.11:39517/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:40:57,257: _ready: http://10.0.0.11:39517/
[xmlrpc][INFO] 2016-01-25 09:40:57,257: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:40:57,258: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 09:40:57,357: registered with master
[rospy.rosout][INFO] 2016-01-25 09:40:57,358: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:40:57,376: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:40:57,383: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 09:40:58,426: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 09:40:58,525: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:40:58,598: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:60924/], count 0
[rospy.internal][INFO] 2016-01-25 09:41:03,064: topic[/tf] adding connection to [http://10.0.0.11:34362/], count 0
[rospy.internal][INFO] 2016-01-25 09:41:03,065: topic[/tf] adding connection to [http://10.0.0.11:57690/], count 1
[rospy.internal][ERROR] 2016-01-25 09:42:08,476: Unable to initiate TCP/IP socket to 10.0.0.11:43623 (http://10.0.0.11:60924/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:42:09,477: Unknown error initiating TCP/IP socket to 10.0.0.11:43623 (http://10.0.0.11:60924/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:42:09,477: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:60924/
[rospy.core][INFO] 2016-01-25 09:42:22,350: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:42:22,376: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:42:22,377: topic[/tf] removing connection to http://10.0.0.11:34362/
[rospy.internal][INFO] 2016-01-25 09:42:22,377: topic[/tf] removing connection to http://10.0.0.11:57690/
[rospy.impl.masterslave][INFO] 2016-01-25 09:42:22,377: signal-2
[rospy.core][INFO] 2016-01-25 09:42:22,998: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 09:48:24,894: init_node, name[/nao_writer], pid[9897]
[xmlrpc][INFO] 2016-01-25 09:48:24,900: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 09:48:24,901: Started XML-RPC server [http://10.0.0.11:44936/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:48:24,901: _ready: http://10.0.0.11:44936/
[rospy.init][INFO] 2016-01-25 09:48:24,902: ROS Slave URI: [http://10.0.0.11:44936/]
[xmlrpc][INFO] 2016-01-25 09:48:24,912: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:48:24,913: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 09:48:25,002: registered with master
[rospy.rosout][INFO] 2016-01-25 09:48:25,002: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:48:25,010: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:48:25,012: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 09:48:25,594: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 09:48:25,692: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:48:26,067: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:44560/], count 0
[rospy.internal][INFO] 2016-01-25 09:48:30,232: topic[/tf] adding connection to [http://10.0.0.11:48467/], count 0
[rospy.internal][INFO] 2016-01-25 09:48:30,236: topic[/tf] adding connection to [http://10.0.0.11:51049/], count 1
[rosout][INFO] 2016-01-25 09:49:04,202: got traj at 1453711744202008008
[rosout][INFO] 2016-01-25 09:49:07,197: executing rest of traj at 1453711747197540998
[rosout][INFO] 2016-01-25 09:49:13,008: Time taken for rest of trajectory: 5.809571981
[rospy.internal][ERROR] 2016-01-25 09:51:04,190: Unable to initiate TCP/IP socket to 10.0.0.11:59208 (http://10.0.0.11:44560/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:51:05,192: Unknown error initiating TCP/IP socket to 10.0.0.11:59208 (http://10.0.0.11:44560/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:51:05,192: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:44560/
[rospy.core][INFO] 2016-01-25 09:51:14,844: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:51:14,860: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:51:14,860: topic[/tf] removing connection to http://10.0.0.11:48467/
[rospy.internal][INFO] 2016-01-25 09:51:14,862: topic[/tf] removing connection to http://10.0.0.11:51049/
[rospy.impl.masterslave][INFO] 2016-01-25 09:51:14,862: signal-2
[rospy.core][INFO] 2016-01-25 09:51:15,484: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 09:51:21,925: init_node, name[/nao_writer], pid[13805]
[xmlrpc][INFO] 2016-01-25 09:51:21,931: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 09:51:21,932: Started XML-RPC server [http://10.0.0.11:50368/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:51:21,933: _ready: http://10.0.0.11:50368/
[rospy.init][INFO] 2016-01-25 09:51:21,933: ROS Slave URI: [http://10.0.0.11:50368/]
[xmlrpc][INFO] 2016-01-25 09:51:21,948: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 09:51:21,955: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 09:51:22,033: registered with master
[rospy.rosout][INFO] 2016-01-25 09:51:22,033: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:51:22,039: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:51:22,044: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 09:51:22,752: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 09:51:22,824: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:51:23,080: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:40981/], count 0
[rospy.internal][INFO] 2016-01-25 09:51:27,342: topic[/tf] adding connection to [http://10.0.0.11:39365/], count 0
[rospy.internal][INFO] 2016-01-25 09:51:27,344: topic[/tf] adding connection to [http://10.0.0.11:48810/], count 1
[rosout][INFO] 2016-01-25 09:52:05,429: got traj at 1453711925429229974
[rosout][INFO] 2016-01-25 09:52:08,422: executing rest of traj at 1453711928422622919
[rosout][INFO] 2016-01-25 09:52:14,227: Time taken for rest of trajectory: 5.803601026
[rosout][INFO] 2016-01-25 09:52:41,500: got traj at 1453711961500552892
[rosout][INFO] 2016-01-25 09:52:44,492: executing rest of traj at 1453711964492274045
[rosout][INFO] 2016-01-25 09:52:50,409: Time taken for rest of trajectory: 5.91632986
[rosout][INFO] 2016-01-25 09:53:09,237: got traj at 1453711989237462997
[rosout][INFO] 2016-01-25 09:53:12,228: executing rest of traj at 1453711992228168964
[rosout][INFO] 2016-01-25 09:53:18,026: Time taken for rest of trajectory: 5.796977997
[rosout][INFO] 2016-01-25 09:53:45,003: got traj at 1453712025003051042
[rosout][INFO] 2016-01-25 09:53:47,998: executing rest of traj at 1453712027998739004
[rosout][INFO] 2016-01-25 09:53:53,805: Time taken for rest of trajectory: 5.805235148
[rospy.internal][ERROR] 2016-01-25 09:54:50,617: Unable to initiate TCP/IP socket to 10.0.0.11:55200 (http://10.0.0.11:40981/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 09:54:51,619: Unknown error initiating TCP/IP socket to 10.0.0.11:55200 (http://10.0.0.11:40981/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 09:54:51,621: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:40981/
[rospy.core][INFO] 2016-01-25 09:55:16,877: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 09:55:16,892: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 09:55:16,892: topic[/tf] removing connection to http://10.0.0.11:39365/
[rospy.internal][WARNING] 2016-01-25 09:55:16,893: Unknown error initiating TCP/IP socket to 10.0.0.11:58583 (http://10.0.0.11:39365/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2016-01-25 09:55:16,893: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2016-01-25 09:55:16,893: topic[/tf] removing connection to http://10.0.0.11:48810/
[rospy.impl.masterslave][INFO] 2016-01-25 09:55:16,893: signal-2
[rospy.core][INFO] 2016-01-25 09:55:17,521: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 09:55:31,559: init_node, name[/nao_writer], pid[20822]
[xmlrpc][INFO] 2016-01-25 09:55:31,568: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 09:55:31,568: Started XML-RPC server [http://10.0.0.11:43253/]
[rospy.impl.masterslave][INFO] 2016-01-25 09:55:31,568: _ready: http://10.0.0.11:43253/
[rospy.init][INFO] 2016-01-25 09:55:31,569: ROS Slave URI: [http://10.0.0.11:43253/]
[rospy.registration][INFO] 2016-01-25 09:55:31,572: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-25 09:55:31,572: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-25 09:55:31,669: registered with master
[rospy.rosout][INFO] 2016-01-25 09:55:31,669: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 09:55:31,675: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 09:55:31,712: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 09:55:32,722: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 09:55:32,804: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 09:55:32,845: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:55417/], count 0
[rospy.internal][INFO] 2016-01-25 09:55:37,345: topic[/tf] adding connection to [http://10.0.0.11:48256/], count 0
[rospy.internal][INFO] 2016-01-25 09:55:37,348: topic[/tf] adding connection to [http://10.0.0.11:58789/], count 1
[rosout][INFO] 2016-01-25 09:56:04,262: got traj at 1453712164262424945
[rosout][INFO] 2016-01-25 09:56:07,254: executing rest of traj at 1453712167254267930
[rosout][INFO] 2016-01-25 09:56:13,065: Time taken for rest of trajectory: 5.809885978
[rosout][INFO] 2016-01-25 09:56:29,333: got traj at 1453712189333880901
[rosout][INFO] 2016-01-25 09:56:32,327: executing rest of traj at 1453712192327536106
[rosout][INFO] 2016-01-25 09:56:38,124: Time taken for rest of trajectory: 5.795505047
[rospy.internal][ERROR] 2016-01-25 10:00:03,827: Unable to initiate TCP/IP socket to 10.0.0.11:54519 (http://10.0.0.11:55417/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:00:04,829: Unknown error initiating TCP/IP socket to 10.0.0.11:54519 (http://10.0.0.11:55417/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:00:04,829: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:55417/
[rospy.core][INFO] 2016-01-25 10:00:22,260: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:00:22,276: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:00:22,277: topic[/tf] removing connection to http://10.0.0.11:48256/
[rospy.internal][INFO] 2016-01-25 10:00:22,277: topic[/tf] removing connection to http://10.0.0.11:58789/
[rospy.impl.masterslave][INFO] 2016-01-25 10:00:22,277: signal-2
[rospy.core][INFO] 2016-01-25 10:00:22,902: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:00:30,863: init_node, name[/nao_writer], pid[29762]
[xmlrpc][INFO] 2016-01-25 10:00:30,879: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:00:30,883: ROS Slave URI: [http://10.0.0.11:38086/]
[xmlrpc][INFO] 2016-01-25 10:00:30,883: Started XML-RPC server [http://10.0.0.11:38086/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:00:30,884: _ready: http://10.0.0.11:38086/
[xmlrpc][INFO] 2016-01-25 10:00:30,890: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:00:30,890: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:00:30,984: registered with master
[rospy.rosout][INFO] 2016-01-25 10:00:30,984: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:00:30,989: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:00:30,994: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:00:31,872: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:00:31,890: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:00:31,901: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:34063/], count 0
[rospy.internal][INFO] 2016-01-25 10:00:36,569: topic[/tf] adding connection to [http://10.0.0.11:60718/], count 0
[rospy.internal][INFO] 2016-01-25 10:00:36,571: topic[/tf] adding connection to [http://10.0.0.11:38071/], count 1
[rosout][INFO] 2016-01-25 10:00:47,335: got traj at 1453712447335544109
[rosout][INFO] 2016-01-25 10:00:50,327: executing rest of traj at 1453712450327503919
[rosout][INFO] 2016-01-25 10:00:56,141: Time taken for rest of trajectory: 5.81278491
[rosout][INFO] 2016-01-25 10:01:08,297: got traj at 1453712468297396898
[rosout][INFO] 2016-01-25 10:01:11,270: executing rest of traj at 1453712471270446062
[rosout][INFO] 2016-01-25 10:01:17,078: Time taken for rest of trajectory: 5.807698965
[rosout][INFO] 2016-01-25 10:01:29,366: got traj at 1453712489366560935
[rosout][INFO] 2016-01-25 10:01:32,359: executing rest of traj at 1453712492359113931
[rosout][INFO] 2016-01-25 10:01:38,157: Time taken for rest of trajectory: 5.797561884
[rosout][INFO] 2016-01-25 10:01:48,349: got traj at 1453712508349055051
[rosout][INFO] 2016-01-25 10:01:51,333: executing rest of traj at 1453712511333123922
[rosout][INFO] 2016-01-25 10:01:58,137: Time taken for rest of trajectory: 6.803180933
[rosout][INFO] 2016-01-25 10:02:15,703: got traj at 1453712535703588962
[rosout][INFO] 2016-01-25 10:02:18,689: executing rest of traj at 1453712538689820051
[rosout][INFO] 2016-01-25 10:02:25,500: Time taken for rest of trajectory: 6.809613943
[rospy.internal][ERROR] 2016-01-25 10:03:41,110: Unable to initiate TCP/IP socket to 10.0.0.11:60719 (http://10.0.0.11:34063/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:03:42,112: Unknown error initiating TCP/IP socket to 10.0.0.11:60719 (http://10.0.0.11:34063/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:03:42,112: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:34063/
[rospy.core][INFO] 2016-01-25 10:03:48,182: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:03:48,196: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:03:48,197: topic[/tf] removing connection to http://10.0.0.11:60718/
[rospy.internal][INFO] 2016-01-25 10:03:48,197: topic[/tf] removing connection to http://10.0.0.11:38071/
[rospy.impl.masterslave][INFO] 2016-01-25 10:03:48,197: signal-2
[rospy.core][INFO] 2016-01-25 10:03:48,313: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:03:52,783: init_node, name[/nao_writer], pid[4707]
[xmlrpc][INFO] 2016-01-25 10:03:52,792: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:03:52,794: ROS Slave URI: [http://10.0.0.11:54678/]
[xmlrpc][INFO] 2016-01-25 10:03:52,794: Started XML-RPC server [http://10.0.0.11:54678/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:03:52,795: _ready: http://10.0.0.11:54678/
[xmlrpc][INFO] 2016-01-25 10:03:52,800: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:03:52,804: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:03:52,895: registered with master
[rospy.rosout][INFO] 2016-01-25 10:03:52,895: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:03:52,934: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:03:52,940: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 10:03:53,466: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:03:53,551: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 10:03:54,340: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:40124/], count 0
[rospy.internal][INFO] 2016-01-25 10:03:58,106: topic[/tf] adding connection to [http://10.0.0.11:39966/], count 0
[rospy.internal][INFO] 2016-01-25 10:03:58,108: topic[/tf] adding connection to [http://10.0.0.11:46820/], count 1
[rosout][INFO] 2016-01-25 10:04:17,261: got traj at 1453712657261737108
[rosout][INFO] 2016-01-25 10:04:20,252: executing rest of traj at 1453712660252351045
[rosout][INFO] 2016-01-25 10:04:28,056: Time taken for rest of trajectory: 7.803484917
[rosout][INFO] 2016-01-25 10:04:47,795: got traj at 1453712687795083999
[rosout][INFO] 2016-01-25 10:04:49,730: executing rest of traj at 1453712689729912042
[rosout][INFO] 2016-01-25 10:04:57,536: Time taken for rest of trajectory: 7.805278062
[rosout][INFO] 2016-01-25 10:05:11,512: got traj at 1453712711511961936
[rosout][INFO] 2016-01-25 10:05:14,499: executing rest of traj at 1453712714499393939
[rosout][INFO] 2016-01-25 10:05:22,317: Time taken for rest of trajectory: 7.817245961
[rosout][INFO] 2016-01-25 10:05:35,807: got traj at 1453712735807243108
[rosout][INFO] 2016-01-25 10:05:38,797: executing rest of traj at 1453712738797068119
[rosout][INFO] 2016-01-25 10:05:46,616: Time taken for rest of trajectory: 7.818218946
[rosout][INFO] 2016-01-25 10:06:02,997: got traj at 1453712762997797012
[rosout][INFO] 2016-01-25 10:06:05,849: executing rest of traj at 1453712765849463939
[rosout][INFO] 2016-01-25 10:06:13,653: Time taken for rest of trajectory: 7.803413868
[rospy.internal][ERROR] 2016-01-25 10:07:03,996: Unable to initiate TCP/IP socket to 10.0.0.11:58862 (http://10.0.0.11:40124/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:07:04,997: Unknown error initiating TCP/IP socket to 10.0.0.11:58862 (http://10.0.0.11:40124/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:07:04,997: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:40124/
[rospy.core][INFO] 2016-01-25 10:07:11,488: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:07:11,516: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:07:11,517: topic[/tf] removing connection to http://10.0.0.11:39966/
[rospy.internal][INFO] 2016-01-25 10:07:11,517: topic[/tf] removing connection to http://10.0.0.11:46820/
[rospy.impl.masterslave][INFO] 2016-01-25 10:07:11,519: signal-2
[rospy.core][INFO] 2016-01-25 10:07:12,140: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:07:17,691: init_node, name[/nao_writer], pid[11953]
[xmlrpc][INFO] 2016-01-25 10:07:17,699: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:07:17,700: ROS Slave URI: [http://10.0.0.11:54481/]
[xmlrpc][INFO] 2016-01-25 10:07:17,700: Started XML-RPC server [http://10.0.0.11:54481/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:07:17,700: _ready: http://10.0.0.11:54481/
[xmlrpc][INFO] 2016-01-25 10:07:17,704: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:07:17,706: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:07:17,800: registered with master
[rospy.rosout][INFO] 2016-01-25 10:07:17,800: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:07:17,835: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:07:17,856: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 10:07:18,403: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:07:18,470: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 10:07:18,877: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:49910/], count 0
[rospy.internal][INFO] 2016-01-25 10:07:23,045: topic[/tf] adding connection to [http://10.0.0.11:53471/], count 0
[rospy.internal][INFO] 2016-01-25 10:07:23,046: topic[/tf] adding connection to [http://10.0.0.11:55405/], count 1
[rosout][INFO] 2016-01-25 10:07:34,146: got traj at 1453712854146673917
[rosout][INFO] 2016-01-25 10:07:37,140: executing rest of traj at 1453712857140001058
[rosout][INFO] 2016-01-25 10:07:42,952: Time taken for rest of trajectory: 5.811582804
[rosout][INFO] 2016-01-25 10:07:54,828: got traj at 1453712874828679084
[rosout][INFO] 2016-01-25 10:07:57,822: executing rest of traj at 1453712877822033882
[rosout][INFO] 2016-01-25 10:08:04,633: Time taken for rest of trajectory: 6.810868025
[rospy.internal][ERROR] 2016-01-25 10:09:16,699: Unable to initiate TCP/IP socket to 10.0.0.11:58338 (http://10.0.0.11:49910/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:09:17,701: Unknown error initiating TCP/IP socket to 10.0.0.11:58338 (http://10.0.0.11:49910/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:09:17,701: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:49910/
[rospy.core][INFO] 2016-01-25 10:09:28,267: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:09:28,279: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:09:28,279: topic[/tf] removing connection to http://10.0.0.11:53471/
[rospy.internal][INFO] 2016-01-25 10:09:28,280: topic[/tf] removing connection to http://10.0.0.11:55405/
[rospy.impl.masterslave][INFO] 2016-01-25 10:09:28,280: signal-2
[rospy.core][INFO] 2016-01-25 10:09:28,419: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:09:32,848: init_node, name[/nao_writer], pid[16252]
[xmlrpc][INFO] 2016-01-25 10:09:32,860: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 10:09:32,861: Started XML-RPC server [http://10.0.0.11:43996/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:09:32,861: _ready: http://10.0.0.11:43996/
[rospy.init][INFO] 2016-01-25 10:09:32,862: ROS Slave URI: [http://10.0.0.11:43996/]
[xmlrpc][INFO] 2016-01-25 10:09:32,866: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:09:32,866: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:09:32,962: registered with master
[rospy.rosout][INFO] 2016-01-25 10:09:32,962: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:09:32,976: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:09:32,980: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:09:33,480: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:09:33,484: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:09:33,858: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:40833/], count 0
[rospy.internal][INFO] 2016-01-25 10:09:38,174: topic[/tf] adding connection to [http://10.0.0.11:48396/], count 0
[rospy.internal][INFO] 2016-01-25 10:09:38,176: topic[/tf] adding connection to [http://10.0.0.11:42498/], count 1
[rosout][INFO] 2016-01-25 10:10:03,140: got traj at 1453713003140142917
[rosout][INFO] 2016-01-25 10:10:06,133: executing rest of traj at 1453713006133101940
[rosout][INFO] 2016-01-25 10:10:11,932: Time taken for rest of trajectory: 5.798539877
[rosout][INFO] 2016-01-25 10:10:23,050: got traj at 1453713023050052881
[rosout][INFO] 2016-01-25 10:10:26,043: executing rest of traj at 1453713026043289899
[rosout][INFO] 2016-01-25 10:10:31,850: Time taken for rest of trajectory: 5.805710078
[rospy.internal][ERROR] 2016-01-25 10:15:06,855: Unable to initiate TCP/IP socket to 10.0.0.11:59663 (http://10.0.0.11:40833/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:15:07,857: Unknown error initiating TCP/IP socket to 10.0.0.11:59663 (http://10.0.0.11:40833/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:15:07,857: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:40833/
[rospy.core][INFO] 2016-01-25 10:15:13,347: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:15:13,370: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:15:13,370: topic[/tf] removing connection to http://10.0.0.11:48396/
[rospy.internal][ERROR] 2016-01-25 10:15:13,371: Unable to initiate TCP/IP socket to 10.0.0.11:37200 (http://10.0.0.11:42498/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-25 10:15:13,372: topic[/tf] removing connection to http://10.0.0.11:42498/
[rospy.topics][ERROR] 2016-01-25 10:15:13,372: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-01-25 10:15:13,373: signal-2
[rospy.core][INFO] 2016-01-25 10:15:13,993: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:15:17,182: init_node, name[/nao_writer], pid[27083]
[xmlrpc][INFO] 2016-01-25 10:15:17,193: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:15:17,195: ROS Slave URI: [http://10.0.0.11:45928/]
[xmlrpc][INFO] 2016-01-25 10:15:17,195: Started XML-RPC server [http://10.0.0.11:45928/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:15:17,196: _ready: http://10.0.0.11:45928/
[xmlrpc][INFO] 2016-01-25 10:15:17,203: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:15:17,204: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:15:17,296: registered with master
[rospy.rosout][INFO] 2016-01-25 10:15:17,296: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:15:17,321: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:15:17,340: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:15:17,472: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:15:18,097: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:15:18,821: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:45741/], count 0
[rospy.internal][INFO] 2016-01-25 10:15:22,737: topic[/tf] adding connection to [http://10.0.0.11:39757/], count 0
[rospy.internal][INFO] 2016-01-25 10:15:22,738: topic[/tf] adding connection to [http://10.0.0.11:42304/], count 1
[rosout][INFO] 2016-01-25 10:15:54,119: got traj at 1453713354119159936
[rosout][INFO] 2016-01-25 10:15:57,111: executing rest of traj at 1453713357111078023
[rosout][INFO] 2016-01-25 10:16:04,926: Time taken for rest of trajectory: 7.813931942
[rosout][INFO] 2016-01-25 10:17:36,401: got traj at 1453713456401109933
[rosout][INFO] 2016-01-25 10:17:39,396: executing rest of traj at 1453713459396100997
[rosout][INFO] 2016-01-25 10:17:47,206: Time taken for rest of trajectory: 7.809288024
[rospy.internal][ERROR] 2016-01-25 10:18:09,903: Unable to initiate TCP/IP socket to 10.0.0.11:55480 (http://10.0.0.11:45741/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:18:10,903: Unknown error initiating TCP/IP socket to 10.0.0.11:55480 (http://10.0.0.11:45741/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:18:10,903: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:45741/
[rospy.core][INFO] 2016-01-25 10:18:22,115: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:18:22,132: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:18:22,132: topic[/tf] removing connection to http://10.0.0.11:39757/
[rospy.internal][INFO] 2016-01-25 10:18:22,132: topic[/tf] removing connection to http://10.0.0.11:42304/
[rospy.impl.masterslave][INFO] 2016-01-25 10:18:22,132: signal-2
[rospy.core][INFO] 2016-01-25 10:18:22,269: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:18:26,660: init_node, name[/nao_writer], pid[538]
[xmlrpc][INFO] 2016-01-25 10:18:26,671: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:18:26,673: ROS Slave URI: [http://10.0.0.11:39089/]
[xmlrpc][INFO] 2016-01-25 10:18:26,673: Started XML-RPC server [http://10.0.0.11:39089/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:18:26,673: _ready: http://10.0.0.11:39089/
[xmlrpc][INFO] 2016-01-25 10:18:26,682: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:18:26,683: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:18:26,773: registered with master
[rospy.rosout][INFO] 2016-01-25 10:18:26,774: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:18:26,778: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:18:26,796: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 10:18:27,508: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:18:27,590: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 10:18:27,692: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:41904/], count 0
[rospy.internal][INFO] 2016-01-25 10:18:32,160: topic[/tf] adding connection to [http://10.0.0.11:56316/], count 0
[rospy.internal][INFO] 2016-01-25 10:18:32,162: topic[/tf] adding connection to [http://10.0.0.11:41115/], count 1
[rosout][INFO] 2016-01-25 10:18:45,931: got traj at 1453713525931499004
[rosout][INFO] 2016-01-25 10:18:48,805: executing rest of traj at 1453713528805015087
[rosout][INFO] 2016-01-25 10:18:54,624: Time taken for rest of trajectory: 5.819440841
[rosout][INFO] 2016-01-25 10:19:10,203: got traj at 1453713550202969074
[rosout][INFO] 2016-01-25 10:19:13,194: executing rest of traj at 1453713553194685935
[rosout][INFO] 2016-01-25 10:19:19,003: Time taken for rest of trajectory: 5.807286978
[rosout][INFO] 2016-01-25 10:19:37,555: got traj at 1453713577554965972
[rosout][INFO] 2016-01-25 10:19:40,545: executing rest of traj at 1453713580545672893
[rosout][INFO] 2016-01-25 10:19:46,344: Time taken for rest of trajectory: 5.798392057
[rosout][INFO] 2016-01-25 10:19:57,890: got traj at 1453713597890397071
[rosout][INFO] 2016-01-25 10:20:00,879: executing rest of traj at 1453713600879498958
[rosout][INFO] 2016-01-25 10:20:06,685: Time taken for rest of trajectory: 5.803861857
[rosout][INFO] 2016-01-25 10:20:16,754: got traj at 1453713616754184007
[rosout][INFO] 2016-01-25 10:20:19,749: executing rest of traj at 1453713619749119043
[rosout][INFO] 2016-01-25 10:20:25,543: Time taken for rest of trajectory: 5.793554067
[rosout][INFO] 2016-01-25 10:21:00,737: got traj at 1453713660737472057
[rosout][INFO] 2016-01-25 10:21:03,729: executing rest of traj at 1453713663729746103
[rosout][INFO] 2016-01-25 10:21:09,541: Time taken for rest of trajectory: 5.811050176
[rospy.internal][ERROR] 2016-01-25 10:22:23,208: Unable to initiate TCP/IP socket to 10.0.0.11:43171 (http://10.0.0.11:41904/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:22:24,209: Unknown error initiating TCP/IP socket to 10.0.0.11:43171 (http://10.0.0.11:41904/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:22:24,210: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:41904/
[rospy.core][INFO] 2016-01-25 10:22:27,237: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:22:27,262: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:22:27,262: topic[/tf] removing connection to http://10.0.0.11:56316/
[rospy.internal][INFO] 2016-01-25 10:22:27,262: topic[/tf] removing connection to http://10.0.0.11:41115/
[rospy.impl.masterslave][INFO] 2016-01-25 10:22:27,263: signal-2
[rospy.core][INFO] 2016-01-25 10:22:27,885: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:22:33,783: init_node, name[/nao_writer], pid[8580]
[xmlrpc][INFO] 2016-01-25 10:22:33,789: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:22:33,799: ROS Slave URI: [http://10.0.0.11:36652/]
[xmlrpc][INFO] 2016-01-25 10:22:33,799: Started XML-RPC server [http://10.0.0.11:36652/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:22:33,799: _ready: http://10.0.0.11:36652/
[xmlrpc][INFO] 2016-01-25 10:22:33,808: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:22:33,816: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:22:33,899: registered with master
[rospy.rosout][INFO] 2016-01-25 10:22:33,900: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:22:33,913: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:22:33,944: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:22:34,887: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:22:34,903: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:22:35,324: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:32869/], count 0
[rospy.internal][INFO] 2016-01-25 10:22:39,541: topic[/tf] adding connection to [http://10.0.0.11:60118/], count 0
[rospy.internal][INFO] 2016-01-25 10:22:39,542: topic[/tf] adding connection to [http://10.0.0.11:52452/], count 1
[rosout][INFO] 2016-01-25 10:22:50,378: got traj at 1453713770378895998
[rosout][INFO] 2016-01-25 10:22:53,370: executing rest of traj at 1453713773370193958
[rosout][INFO] 2016-01-25 10:23:00,180: Time taken for rest of trajectory: 6.808812857
[rosout][INFO] 2016-01-25 10:23:15,453: got traj at 1453713795453154087
[rosout][INFO] 2016-01-25 10:23:18,443: executing rest of traj at 1453713798443629026
[rosout][INFO] 2016-01-25 10:23:25,242: Time taken for rest of trajectory: 6.797644138
[rospy.internal][ERROR] 2016-01-25 10:24:08,667: Unable to initiate TCP/IP socket to 10.0.0.11:59137 (http://10.0.0.11:32869/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:24:09,668: Unknown error initiating TCP/IP socket to 10.0.0.11:59137 (http://10.0.0.11:32869/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:24:09,668: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:32869/
[rospy.core][INFO] 2016-01-25 10:24:11,425: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:24:11,438: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:24:11,438: topic[/tf] removing connection to http://10.0.0.11:60118/
[rospy.internal][INFO] 2016-01-25 10:24:11,438: topic[/tf] removing connection to http://10.0.0.11:52452/
[rospy.impl.masterslave][INFO] 2016-01-25 10:24:11,438: signal-2
[rospy.core][INFO] 2016-01-25 10:24:11,556: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:26:56,941: init_node, name[/nao_writer], pid[12834]
[xmlrpc][INFO] 2016-01-25 10:26:56,947: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 10:26:56,948: Started XML-RPC server [http://10.0.0.11:35352/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:26:56,949: _ready: http://10.0.0.11:35352/
[rospy.init][INFO] 2016-01-25 10:26:56,949: ROS Slave URI: [http://10.0.0.11:35352/]
[rospy.registration][INFO] 2016-01-25 10:26:56,953: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-25 10:26:56,954: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-25 10:26:57,049: registered with master
[rospy.rosout][INFO] 2016-01-25 10:26:57,050: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:26:57,060: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:26:57,072: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:26:57,423: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:26:57,426: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:26:58,388: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:40475/], count 0
[rospy.internal][INFO] 2016-01-25 10:27:02,103: topic[/tf] adding connection to [http://10.0.0.11:37210/], count 0
[rospy.internal][INFO] 2016-01-25 10:27:02,103: topic[/tf] adding connection to [http://10.0.0.11:36624/], count 1
[rospy.internal][INFO] 2016-01-25 10:27:02,106: topic[/tf] adding connection to [http://10.0.0.11:54432/], count 2
[rospy.internal][INFO] 2016-01-25 10:27:02,107: topic[/tf] adding connection to [http://10.0.0.11:56425/], count 3
[rospy.internal][INFO] 2016-01-25 10:27:02,107: topic[/tf] adding connection to [http://10.0.0.11:37401/], count 3
[rospy.internal][INFO] 2016-01-25 10:27:02,109: topic[/tf] adding connection to [http://10.0.0.11:47474/], count 4
[rospy.internal][INFO] 2016-01-25 10:27:02,109: topic[/tf] adding connection to [http://10.0.0.11:33542/], count 5
[rospy.internal][INFO] 2016-01-25 10:27:02,110: topic[/tf] adding connection to [http://10.0.0.11:37380/], count 6
[rospy.internal][INFO] 2016-01-25 10:27:02,111: topic[/tf] adding connection to [http://10.0.0.11:47475/], count 7
[rospy.internal][INFO] 2016-01-25 10:27:02,112: topic[/tf] adding connection to [http://10.0.0.11:33621/], count 8
[rosout][INFO] 2016-01-25 10:27:38,769: got traj at 1453714058769143104
[rosout][INFO] 2016-01-25 10:27:41,763: executing rest of traj at 1453714061763453960
[rosout][INFO] 2016-01-25 10:27:47,555: Time taken for rest of trajectory: 5.791841031
[rosout][INFO] 2016-01-25 10:28:33,244: got traj at 1453714113244571924
[rosout][INFO] 2016-01-25 10:28:36,235: executing rest of traj at 1453714116235723972
[rosout][INFO] 2016-01-25 10:28:42,036: Time taken for rest of trajectory: 5.800023079
[rosout][INFO] 2016-01-25 10:29:36,069: got traj at 1453714176069916009
[rosout][INFO] 2016-01-25 10:29:39,063: executing rest of traj at 1453714179063642024
[rosout][INFO] 2016-01-25 10:29:44,874: Time taken for rest of trajectory: 5.810117006
[rosout][INFO] 2016-01-25 10:30:32,640: got traj at 1453714232640388965
[rosout][INFO] 2016-01-25 10:30:35,263: executing rest of traj at 1453714235263457059
[rosout][INFO] 2016-01-25 10:30:43,073: Time taken for rest of trajectory: 7.809821129
[rosout][INFO] 2016-01-25 10:31:26,679: got traj at 1453714286679281949
[rosout][INFO] 2016-01-25 10:31:29,667: executing rest of traj at 1453714289667606115
[rosout][INFO] 2016-01-25 10:31:37,473: Time taken for rest of trajectory: 7.805601836
[rosout][INFO] 2016-01-25 10:32:20,003: got traj at 1453714340003412961
[rosout][INFO] 2016-01-25 10:32:22,990: executing rest of traj at 1453714342990674018
[rosout][INFO] 2016-01-25 10:32:29,792: Time taken for rest of trajectory: 6.8014431
[rosout][INFO] 2016-01-25 10:33:22,763: got traj at 1453714402763717889
[rosout][INFO] 2016-01-25 10:33:25,755: executing rest of traj at 1453714405755461931
[rosout][INFO] 2016-01-25 10:33:32,550: Time taken for rest of trajectory: 6.794655085
[rosout][INFO] 2016-01-25 10:34:32,622: got traj at 1453714472622059106
[rosout][INFO] 2016-01-25 10:34:35,615: executing rest of traj at 1453714475615849018
[rosout][INFO] 2016-01-25 10:34:42,410: Time taken for rest of trajectory: 6.794564009
[rosout][INFO] 2016-01-25 10:35:25,625: got traj at 1453714525625139951
[rosout][INFO] 2016-01-25 10:35:28,618: executing rest of traj at 1453714528618587970
[rosout][INFO] 2016-01-25 10:35:34,449: Time taken for rest of trajectory: 5.830200195
[rosout][INFO] 2016-01-25 10:36:28,089: got traj at 1453714588089436054
[rosout][INFO] 2016-01-25 10:36:31,080: executing rest of traj at 1453714591080538988
[rosout][INFO] 2016-01-25 10:36:36,887: Time taken for rest of trajectory: 5.806551933
[rosout][INFO] 2016-01-25 10:37:16,215: got traj at 1453714636215609073
[rosout][INFO] 2016-01-25 10:37:19,076: executing rest of traj at 1453714639076402902
[rosout][INFO] 2016-01-25 10:37:24,867: Time taken for rest of trajectory: 5.790923119
[rosout][INFO] 2016-01-25 10:37:55,275: got traj at 1453714675275882959
[rosout][INFO] 2016-01-25 10:37:58,268: executing rest of traj at 1453714678268475055
[rosout][INFO] 2016-01-25 10:38:04,066: Time taken for rest of trajectory: 5.797749042
[rosout][INFO] 2016-01-25 10:39:01,370: got traj at 1453714741370510101
[rosout][INFO] 2016-01-25 10:39:04,360: executing rest of traj at 1453714744360539913
[rosout][INFO] 2016-01-25 10:39:10,166: Time taken for rest of trajectory: 5.805015087
[rosout][INFO] 2016-01-25 10:39:41,454: got traj at 1453714781453973054
[rosout][INFO] 2016-01-25 10:39:44,445: executing rest of traj at 1453714784445296049
[rosout][INFO] 2016-01-25 10:39:50,245: Time taken for rest of trajectory: 5.800176859
[rosout][INFO] 2016-01-25 10:40:51,676: got traj at 1453714851676744937
[rosout][INFO] 2016-01-25 10:40:54,671: executing rest of traj at 1453714854671458959
[rosout][INFO] 2016-01-25 10:41:00,465: Time taken for rest of trajectory: 5.793936968
[rospy.internal][ERROR] 2016-01-25 10:41:17,202: Unable to initiate TCP/IP socket to 10.0.0.11:36312 (http://10.0.0.11:40475/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 10:41:18,203: Unknown error initiating TCP/IP socket to 10.0.0.11:36312 (http://10.0.0.11:40475/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 10:41:18,203: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:40475/
[rospy.core][INFO] 2016-01-25 10:42:15,551: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 10:42:15,569: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 10:42:15,569: topic[/tf] removing connection to http://10.0.0.11:37210/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:36624/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:54432/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:56425/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:37401/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:47474/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:33542/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:37380/
[rospy.internal][INFO] 2016-01-25 10:42:15,570: topic[/tf] removing connection to http://10.0.0.11:47475/
[rospy.internal][ERROR] 2016-01-25 10:42:15,573: Unable to initiate TCP/IP socket to 10.0.0.11:58988 (http://10.0.0.11:33621/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-25 10:42:15,573: topic[/tf] removing connection to http://10.0.0.11:33621/
[rospy.impl.masterslave][INFO] 2016-01-25 10:42:15,573: signal-2
[rospy.core][INFO] 2016-01-25 10:42:16,193: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 10:51:28,937: init_node, name[/nao_writer], pid[8533]
[xmlrpc][INFO] 2016-01-25 10:51:28,938: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 10:51:28,938: ROS Slave URI: [http://10.0.0.11:53271/]
[xmlrpc][INFO] 2016-01-25 10:51:28,938: Started XML-RPC server [http://10.0.0.11:53271/]
[rospy.impl.masterslave][INFO] 2016-01-25 10:51:28,939: _ready: http://10.0.0.11:53271/
[xmlrpc][INFO] 2016-01-25 10:51:28,939: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 10:51:28,939: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 10:51:29,039: registered with master
[rospy.rosout][INFO] 2016-01-25 10:51:29,039: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 10:51:29,066: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 10:51:29,072: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 10:51:29,183: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 10:51:29,821: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 10:51:30,097: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:41227/], count 0
[rospy.internal][INFO] 2016-01-25 10:51:34,411: topic[/tf] adding connection to [http://10.0.0.11:49435/], count 0
[rospy.internal][INFO] 2016-01-25 10:51:34,414: topic[/tf] adding connection to [http://10.0.0.11:42721/], count 1
[rospy.internal][INFO] 2016-01-25 10:51:34,414: topic[/tf] adding connection to [http://10.0.0.11:45960/], count 1
[rospy.internal][INFO] 2016-01-25 10:51:34,415: topic[/tf] adding connection to [http://10.0.0.11:40455/], count 1
[rospy.internal][INFO] 2016-01-25 10:51:34,415: topic[/tf] adding connection to [http://10.0.0.11:44517/], count 2
[rospy.internal][INFO] 2016-01-25 10:51:34,417: topic[/tf] adding connection to [http://10.0.0.11:49207/], count 5
[rospy.internal][INFO] 2016-01-25 10:51:34,418: topic[/tf] adding connection to [http://10.0.0.11:54943/], count 6
[rospy.internal][INFO] 2016-01-25 10:51:34,419: topic[/tf] adding connection to [http://10.0.0.11:48500/], count 6
[rospy.internal][INFO] 2016-01-25 10:51:34,421: topic[/tf] adding connection to [http://10.0.0.11:57340/], count 8
[rospy.internal][INFO] 2016-01-25 10:51:34,422: topic[/tf] adding connection to [http://10.0.0.11:43501/], count 9
[rosout][INFO] 2016-01-25 10:51:59,259: got traj at 1453715519259258031
[rosout][INFO] 2016-01-25 10:52:02,251: executing rest of traj at 1453715522251396894
[rosout][INFO] 2016-01-25 10:52:08,055: Time taken for rest of trajectory: 5.803987027
[rosout][INFO] 2016-01-25 10:52:38,260: got traj at 1453715558260756969
[rosout][INFO] 2016-01-25 10:52:41,253: executing rest of traj at 1453715561253447055
[rosout][INFO] 2016-01-25 10:52:47,056: Time taken for rest of trajectory: 5.802124977
[rosout][INFO] 2016-01-25 10:53:24,762: got traj at 1453715604762659072
[rosout][INFO] 2016-01-25 10:53:27,756: executing rest of traj at 1453715607756956100
[rosout][INFO] 2016-01-25 10:53:33,574: Time taken for rest of trajectory: 5.816637993
[rosout][INFO] 2016-01-25 10:54:04,867: got traj at 1453715644867579936
[rosout][INFO] 2016-01-25 10:54:07,862: executing rest of traj at 1453715647862329959
[rosout][INFO] 2016-01-25 10:54:13,673: Time taken for rest of trajectory: 5.810283184
[rosout][INFO] 2016-01-25 10:54:41,842: got traj at 1453715681842417001
[rosout][INFO] 2016-01-25 10:54:44,835: executing rest of traj at 1453715684835474014
[rosout][INFO] 2016-01-25 10:54:50,687: Time taken for rest of trajectory: 5.850886822
[rosout][INFO] 2016-01-25 10:55:17,181: got traj at 1453715717181895017
[rosout][INFO] 2016-01-25 10:55:20,175: executing rest of traj at 1453715720175462961
[rosout][INFO] 2016-01-25 10:55:25,971: Time taken for rest of trajectory: 5.795915127
[rosout][INFO] 2016-01-25 10:55:56,454: got traj at 1453715756454293012
[rosout][INFO] 2016-01-25 10:55:59,444: executing rest of traj at 1453715759444634914
[rosout][INFO] 2016-01-25 10:56:05,252: Time taken for rest of trajectory: 5.807865858
[rosout][INFO] 2016-01-25 10:56:29,790: got traj at 1453715789790031909
[rosout][INFO] 2016-01-25 10:56:32,784: executing rest of traj at 1453715792784668922
[rosout][INFO] 2016-01-25 10:56:38,593: Time taken for rest of trajectory: 5.807952165
[rosout][INFO] 2016-01-25 10:57:04,964: got traj at 1453715824964153051
[rosout][INFO] 2016-01-25 10:57:07,958: executing rest of traj at 1453715827958636045
[rosout][INFO] 2016-01-25 10:57:13,752: Time taken for rest of trajectory: 5.793357134
[rosout][INFO] 2016-01-25 10:57:41,552: got traj at 1453715861552896976
[rosout][INFO] 2016-01-25 10:57:44,545: executing rest of traj at 1453715864545113086
[rosout][INFO] 2016-01-25 10:57:50,514: Time taken for rest of trajectory: 5.968466043
[rosout][INFO] 2016-01-25 10:58:18,082: got traj at 1453715898082551002
[rosout][INFO] 2016-01-25 10:58:21,075: executing rest of traj at 1453715901075454950
[rosout][INFO] 2016-01-25 10:58:26,889: Time taken for rest of trajectory: 5.813325166
[rosout][INFO] 2016-01-25 10:58:52,392: got traj at 1453715932392885923
[rosout][INFO] 2016-01-25 10:58:55,384: executing rest of traj at 1453715935383984088
[rosout][INFO] 2016-01-25 10:59:01,188: Time taken for rest of trajectory: 5.804116011
[rosout][INFO] 2016-01-25 10:59:26,796: got traj at 1453715966796648025
[rosout][INFO] 2016-01-25 10:59:29,789: executing rest of traj at 1453715969789258956
[rosout][INFO] 2016-01-25 10:59:35,609: Time taken for rest of trajectory: 5.819100857
[rosout][INFO] 2016-01-25 11:00:03,451: got traj at 1453716003451839923
[rosout][INFO] 2016-01-25 11:00:06,445: executing rest of traj at 1453716006445035934
[rosout][INFO] 2016-01-25 11:00:14,248: Time taken for rest of trajectory: 7.802397013
[rosout][INFO] 2016-01-25 11:00:50,735: got traj at 1453716050735611915
[rosout][INFO] 2016-01-25 11:00:53,678: executing rest of traj at 1453716053678330898
[rosout][INFO] 2016-01-25 11:01:01,489: Time taken for rest of trajectory: 7.81061697
[rosout][INFO] 2016-01-25 11:01:30,951: got traj at 1453716090951076030
[rosout][INFO] 2016-01-25 11:01:33,943: executing rest of traj at 1453716093943454027
[rosout][INFO] 2016-01-25 11:01:41,746: Time taken for rest of trajectory: 7.802412033
[rosout][INFO] 2016-01-25 11:02:16,775: got traj at 1453716136774971008
[rosout][INFO] 2016-01-25 11:02:19,743: executing rest of traj at 1453716139743722915
[rosout][INFO] 2016-01-25 11:02:27,546: Time taken for rest of trajectory: 7.802088976
[rosout][INFO] 2016-01-25 11:03:00,218: got traj at 1453716180218914031
[rosout][INFO] 2016-01-25 11:03:03,177: executing rest of traj at 1453716183177596092
[rosout][INFO] 2016-01-25 11:03:11,007: Time taken for rest of trajectory: 7.828599215
[rospy.internal][ERROR] 2016-01-25 11:03:24,992: Unable to initiate TCP/IP socket to 10.0.0.11:41305 (http://10.0.0.11:41227/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 11:03:26,004: Unknown error initiating TCP/IP socket to 10.0.0.11:41305 (http://10.0.0.11:41227/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 11:03:26,005: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:41227/
[rospy.internal][WARNING] 2016-01-25 11:03:42,221: Unknown error initiating TCP/IP socket to 10.0.0.11:36534 (http://10.0.0.11:44517/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,221: topic[/tf] removing connection to http://10.0.0.11:44517/
[rospy.internal][WARNING] 2016-01-25 11:03:42,223: Unknown error initiating TCP/IP socket to 10.0.0.11:52452 (http://10.0.0.11:48500/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,223: topic[/tf] removing connection to http://10.0.0.11:48500/
[rospy.internal][WARNING] 2016-01-25 11:03:42,223: Unknown error initiating TCP/IP socket to 10.0.0.11:42316 (http://10.0.0.11:45960/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,224: topic[/tf] removing connection to http://10.0.0.11:45960/
[rospy.internal][WARNING] 2016-01-25 11:03:42,272: Unknown error initiating TCP/IP socket to 10.0.0.11:52061 (http://10.0.0.11:57340/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,272: topic[/tf] removing connection to http://10.0.0.11:57340/
[rospy.internal][WARNING] 2016-01-25 11:03:42,351: Unknown error initiating TCP/IP socket to 10.0.0.11:36027 (http://10.0.0.11:54943/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,351: topic[/tf] removing connection to http://10.0.0.11:54943/
[rospy.internal][WARNING] 2016-01-25 11:03:42,358: Unknown error initiating TCP/IP socket to 10.0.0.11:54725 (http://10.0.0.11:43501/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,358: topic[/tf] removing connection to http://10.0.0.11:43501/
[rospy.internal][WARNING] 2016-01-25 11:03:42,392: Unknown error initiating TCP/IP socket to 10.0.0.11:46757 (http://10.0.0.11:49207/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,392: topic[/tf] removing connection to http://10.0.0.11:49207/
[rospy.internal][WARNING] 2016-01-25 11:03:42,813: Unknown error initiating TCP/IP socket to 10.0.0.11:44689 (http://10.0.0.11:40455/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:03:42,813: topic[/tf] removing connection to http://10.0.0.11:40455/
[rospy.core][INFO] 2016-01-25 11:03:48,455: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-25 11:03:48,466: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 11:03:48,467: topic[/tf] removing connection to http://10.0.0.11:49435/
[rospy.internal][WARNING] 2016-01-25 11:03:48,467: Unknown error initiating TCP/IP socket to 10.0.0.11:47270 (http://10.0.0.11:49435/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2016-01-25 11:03:48,468: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2016-01-25 11:03:48,468: topic[/tf] removing connection to http://10.0.0.11:42721/
[rospy.impl.masterslave][INFO] 2016-01-25 11:03:48,469: signal-2
[rospy.core][INFO] 2016-01-25 11:03:48,634: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 11:12:16,586: init_node, name[/nao_writer], pid[509]
[xmlrpc][INFO] 2016-01-25 11:12:16,588: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-25 11:12:16,588: ROS Slave URI: [http://10.0.0.11:45491/]
[xmlrpc][INFO] 2016-01-25 11:12:16,588: Started XML-RPC server [http://10.0.0.11:45491/]
[rospy.impl.masterslave][INFO] 2016-01-25 11:12:16,588: _ready: http://10.0.0.11:45491/
[rospy.registration][INFO] 2016-01-25 11:12:16,616: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-25 11:12:16,616: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-25 11:12:16,689: registered with master
[rospy.rosout][INFO] 2016-01-25 11:12:16,689: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 11:12:16,708: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 11:12:16,731: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-25 11:12:17,306: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 11:12:17,400: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-25 11:12:18,334: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:34011/], count 0
[rospy.internal][INFO] 2016-01-25 11:12:21,997: topic[/tf] adding connection to [http://10.0.0.11:57039/], count 0
[rospy.internal][INFO] 2016-01-25 11:12:21,998: topic[/tf] adding connection to [http://10.0.0.11:57292/], count 0
[rospy.internal][INFO] 2016-01-25 11:12:21,998: topic[/tf] adding connection to [http://10.0.0.11:42266/], count 1
[rospy.internal][INFO] 2016-01-25 11:12:22,000: topic[/tf] adding connection to [http://10.0.0.11:50810/], count 3
[rospy.internal][INFO] 2016-01-25 11:12:22,002: topic[/tf] adding connection to [http://10.0.0.11:41056/], count 4
[rospy.internal][INFO] 2016-01-25 11:12:22,003: topic[/tf] adding connection to [http://10.0.0.11:45022/], count 5
[rospy.internal][INFO] 2016-01-25 11:12:22,004: topic[/tf] adding connection to [http://10.0.0.11:53134/], count 5
[rospy.internal][INFO] 2016-01-25 11:12:22,005: topic[/tf] adding connection to [http://10.0.0.11:32879/], count 5
[rospy.internal][INFO] 2016-01-25 11:12:22,009: topic[/tf] adding connection to [http://10.0.0.11:47440/], count 8
[rospy.internal][INFO] 2016-01-25 11:12:22,010: topic[/tf] adding connection to [http://10.0.0.11:52617/], count 9
[rosout][INFO] 2016-01-25 11:12:56,293: got traj at 1453716776293355941
[rosout][INFO] 2016-01-25 11:12:58,889: executing rest of traj at 1453716778889028072
[rosout][INFO] 2016-01-25 11:13:04,698: Time taken for rest of trajectory: 5.808668136
[rosout][INFO] 2016-01-25 11:13:39,765: got traj at 1453716819765655994
[rosout][INFO] 2016-01-25 11:13:42,803: executing rest of traj at 1453716822803806066
[rosout][INFO] 2016-01-25 11:13:48,624: Time taken for rest of trajectory: 5.819884062
[rosout][INFO] 2016-01-25 11:14:32,559: got traj at 1453716872559112071
[rosout][INFO] 2016-01-25 11:14:35,517: executing rest of traj at 1453716875517910957
[rosout][INFO] 2016-01-25 11:14:41,316: Time taken for rest of trajectory: 5.798505068
[rosout][INFO] 2016-01-25 11:15:20,167: got traj at 1453716920167705059
[rosout][INFO] 2016-01-25 11:15:23,162: executing rest of traj at 1453716923162679910
[rosout][INFO] 2016-01-25 11:15:28,954: Time taken for rest of trajectory: 5.791203022
[rosout][INFO] 2016-01-25 11:16:00,505: got traj at 1453716960505455017
[rosout][INFO] 2016-01-25 11:16:03,503: executing rest of traj at 1453716963503462076
[rosout][INFO] 2016-01-25 11:16:09,313: Time taken for rest of trajectory: 5.809849977
[rosout][INFO] 2016-01-25 11:16:48,576: got traj at 1453717008576092004
[rosout][INFO] 2016-01-25 11:16:51,437: executing rest of traj at 1453717011437350034
[rosout][INFO] 2016-01-25 11:16:57,233: Time taken for rest of trajectory: 5.79583478
[rosout][INFO] 2016-01-25 11:17:20,307: got traj at 1453717040307167053
[rosout][INFO] 2016-01-25 11:17:23,277: executing rest of traj at 1453717043277599096
[rosout][INFO] 2016-01-25 11:17:29,072: Time taken for rest of trajectory: 5.794700861
[rosout][INFO] 2016-01-25 11:17:59,312: got traj at 1453717079312036037
[rosout][INFO] 2016-01-25 11:18:02,295: executing rest of traj at 1453717082295883893
[rosout][INFO] 2016-01-25 11:18:08,114: Time taken for rest of trajectory: 5.818054915
[rosout][INFO] 2016-01-25 11:18:35,583: got traj at 1453717115583839893
[rosout][INFO] 2016-01-25 11:18:38,547: executing rest of traj at 1453717118547466993
[rosout][INFO] 2016-01-25 11:18:44,351: Time taken for rest of trajectory: 5.803296804
[rosout][INFO] 2016-01-25 11:19:08,817: got traj at 1453717148817814111
[rosout][INFO] 2016-01-25 11:19:11,810: executing rest of traj at 1453717151810548067
[rosout][INFO] 2016-01-25 11:19:17,611: Time taken for rest of trajectory: 5.800617934
[rosout][INFO] 2016-01-25 11:19:53,392: got traj at 1453717193392576932
[rosout][INFO] 2016-01-25 11:19:56,384: executing rest of traj at 1453717196384593963
[rosout][INFO] 2016-01-25 11:20:02,191: Time taken for rest of trajectory: 5.806721926
[rosout][INFO] 2016-01-25 11:20:32,433: got traj at 1453717232433872938
[rosout][INFO] 2016-01-25 11:20:35,425: executing rest of traj at 1453717235425648927
[rosout][INFO] 2016-01-25 11:20:41,230: Time taken for rest of trajectory: 5.804764986
[rosout][INFO] 2016-01-25 11:21:07,944: got traj at 1453717267944633960
[rosout][INFO] 2016-01-25 11:21:10,944: executing rest of traj at 1453717270944359064
[rosout][INFO] 2016-01-25 11:21:16,751: Time taken for rest of trajectory: 5.80563116
[rosout][INFO] 2016-01-25 11:21:41,322: got traj at 1453717301322117090
[rosout][INFO] 2016-01-25 11:21:44,303: executing rest of traj at 1453717304303472042
[rosout][INFO] 2016-01-25 11:21:50,108: Time taken for rest of trajectory: 5.804176092
[rosout][INFO] 2016-01-25 11:22:14,005: got traj at 1453717334005033016
[rosout][INFO] 2016-01-25 11:22:16,998: executing rest of traj at 1453717336997960090
[rosout][INFO] 2016-01-25 11:22:22,807: Time taken for rest of trajectory: 5.809460878
[rosout][INFO] 2016-01-25 11:22:54,044: got traj at 1453717374044385910
[rosout][INFO] 2016-01-25 11:22:56,801: executing rest of traj at 1453717376801266908
[rosout][INFO] 2016-01-25 11:23:02,608: Time taken for rest of trajectory: 5.806723833
[rosout][INFO] 2016-01-25 11:23:29,023: got traj at 1453717408999429941
[rosout][INFO] 2016-01-25 11:23:31,993: executing rest of traj at 1453717411993390083
[rosout][INFO] 2016-01-25 11:23:37,786: Time taken for rest of trajectory: 5.792695045
[rosout][INFO] 2016-01-25 11:24:09,297: got traj at 1453717449297661066
[rosout][INFO] 2016-01-25 11:24:12,290: executing rest of traj at 1453717452290204048
[rosout][INFO] 2016-01-25 11:24:18,086: Time taken for rest of trajectory: 5.796207905
[rosout][INFO] 2016-01-25 11:24:40,318: got traj at 1453717480318144083
[rosout][INFO] 2016-01-25 11:24:43,311: executing rest of traj at 1453717483311465024
[rosout][INFO] 2016-01-25 11:24:49,105: Time taken for rest of trajectory: 5.793483019
[rospy.internal][ERROR] 2016-01-25 11:25:23,814: Unable to initiate TCP/IP socket to 10.0.0.11:56060 (http://10.0.0.11:34011/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 11:25:24,815: Unknown error initiating TCP/IP socket to 10.0.0.11:56060 (http://10.0.0.11:34011/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 11:25:24,815: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:34011/
[rospy.core][INFO] 2016-01-25 11:26:16,258: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2016-01-25 11:26:16,271: Unknown error initiating TCP/IP socket to 10.0.0.11:40706 (http://10.0.0.11:52617/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:26:16,271: topic[/tf] removing connection to http://10.0.0.11:52617/
[rospy.internal][INFO] 2016-01-25 11:26:16,274: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:57039/
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:57292/
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:42266/
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:50810/
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:41056/
[rospy.internal][INFO] 2016-01-25 11:26:16,275: topic[/tf] removing connection to http://10.0.0.11:45022/
[rospy.internal][INFO] 2016-01-25 11:26:16,276: topic[/tf] removing connection to http://10.0.0.11:53134/
[rospy.internal][INFO] 2016-01-25 11:26:16,276: topic[/tf] removing connection to http://10.0.0.11:32879/
[rospy.internal][INFO] 2016-01-25 11:26:16,276: topic[/tf] removing connection to http://10.0.0.11:47440/
[rospy.impl.masterslave][INFO] 2016-01-25 11:26:16,276: signal-2
[rospy.core][INFO] 2016-01-25 11:26:16,395: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-25 11:34:36,710: init_node, name[/nao_writer], pid[27156]
[xmlrpc][INFO] 2016-01-25 11:34:36,715: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-25 11:34:36,715: Started XML-RPC server [http://10.0.0.11:49214/]
[rospy.impl.masterslave][INFO] 2016-01-25 11:34:36,716: _ready: http://10.0.0.11:49214/
[rospy.init][INFO] 2016-01-25 11:34:36,719: ROS Slave URI: [http://10.0.0.11:49214/]
[xmlrpc][INFO] 2016-01-25 11:34:36,731: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-25 11:34:36,732: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-25 11:34:36,819: registered with master
[rospy.rosout][INFO] 2016-01-25 11:34:36,820: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-25 11:34:36,849: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-25 11:34:36,862: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-25 11:34:37,564: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-01-25 11:34:37,577: Subscribed to robotHasFallen event
[rospy.internal][INFO] 2016-01-25 11:34:37,702: topic[/write_traj_downsampled] adding connection to [http://10.0.0.11:44466/], count 0
[rospy.internal][INFO] 2016-01-25 11:34:42,166: topic[/tf] adding connection to [http://10.0.0.11:49439/], count 0
[rospy.internal][INFO] 2016-01-25 11:34:42,167: topic[/tf] adding connection to [http://10.0.0.11:41840/], count 1
[rosout][INFO] 2016-01-25 11:34:57,820: got traj at 1453718097820368051
[rosout][INFO] 2016-01-25 11:35:00,813: executing rest of traj at 1453718100813523054
[rospy.internal][INFO] 2016-01-25 11:35:01,085: topic[/tf] adding connection to [http://10.0.0.11:56038/], count 2
[rospy.internal][INFO] 2016-01-25 11:35:01,086: topic[/tf] adding connection to [http://10.0.0.11:33737/], count 3
[rospy.internal][INFO] 2016-01-25 11:35:01,089: topic[/tf] adding connection to [http://10.0.0.11:48801/], count 4
[rospy.internal][INFO] 2016-01-25 11:35:01,203: topic[/tf] adding connection to [http://10.0.0.11:32873/], count 5
[rospy.internal][INFO] 2016-01-25 11:35:01,208: topic[/tf] adding connection to [http://10.0.0.11:57831/], count 6
[rospy.internal][INFO] 2016-01-25 11:35:01,213: topic[/tf] adding connection to [http://10.0.0.11:57999/], count 7
[rospy.internal][INFO] 2016-01-25 11:35:01,220: topic[/tf] adding connection to [http://10.0.0.11:40819/], count 8
[rospy.internal][INFO] 2016-01-25 11:35:01,296: topic[/tf] adding connection to [http://10.0.0.11:39218/], count 9
[rosout][INFO] 2016-01-25 11:35:06,616: Time taken for rest of trajectory: 5.802448988
[rosout][INFO] 2016-01-25 11:35:39,846: got traj at 1453718139846690893
[rosout][INFO] 2016-01-25 11:35:42,841: executing rest of traj at 1453718142841388940
[rosout][INFO] 2016-01-25 11:35:48,635: Time taken for rest of trajectory: 5.793951035
[rosout][INFO] 2016-01-25 11:36:13,085: got traj at 1453718173085772037
[rosout][INFO] 2016-01-25 11:36:16,078: executing rest of traj at 1453718176078156948
[rosout][INFO] 2016-01-25 11:36:21,875: Time taken for rest of trajectory: 5.79739499
[rosout][INFO] 2016-01-25 11:36:58,467: got traj at 1453718218467192888
[rosout][INFO] 2016-01-25 11:37:01,458: executing rest of traj at 1453718221458194017
[rosout][INFO] 2016-01-25 11:37:07,256: Time taken for rest of trajectory: 5.797762156
[rosout][INFO] 2016-01-25 11:37:23,145: got traj at 1453718243145879983
[rosout][INFO] 2016-01-25 11:37:26,140: executing rest of traj at 1453718246140822887
[rosout][INFO] 2016-01-25 11:37:31,935: Time taken for rest of trajectory: 5.79430294
[rosout][INFO] 2016-01-25 11:37:53,111: got traj at 1453718273111305952
[rosout][INFO] 2016-01-25 11:37:56,105: executing rest of traj at 1453718276105664014
[rosout][INFO] 2016-01-25 11:38:01,913: Time taken for rest of trajectory: 5.807679892
[rosout][INFO] 2016-01-25 11:38:30,626: got traj at 1453718310626825094
[rosout][INFO] 2016-01-25 11:38:33,481: executing rest of traj at 1453718313481950998
[rosout][INFO] 2016-01-25 11:38:39,273: Time taken for rest of trajectory: 5.791177988
[rosout][INFO] 2016-01-25 11:39:02,475: got traj at 1453718342475589990
[rosout][INFO] 2016-01-25 11:39:05,466: executing rest of traj at 1453718345466871976
[rosout][INFO] 2016-01-25 11:39:11,273: Time taken for rest of trajectory: 5.80562687
[rosout][INFO] 2016-01-25 11:39:25,075: got traj at 1453718365075500965
[rosout][INFO] 2016-01-25 11:39:28,067: executing rest of traj at 1453718368067456960
[rosout][INFO] 2016-01-25 11:39:33,873: Time taken for rest of trajectory: 5.806050062
[rosout][INFO] 2016-01-25 11:39:53,138: got traj at 1453718393138596057
[rosout][INFO] 2016-01-25 11:39:56,131: executing rest of traj at 1453718396131576061
[rosout][INFO] 2016-01-25 11:40:01,933: Time taken for rest of trajectory: 5.801730156
[rosout][INFO] 2016-01-25 11:40:22,972: got traj at 1453718422972753047
[rosout][INFO] 2016-01-25 11:40:25,964: executing rest of traj at 1453718425964567899
[rosout][INFO] 2016-01-25 11:40:32,093: Time taken for rest of trajectory: 6.128301144
[rosout][INFO] 2016-01-25 11:40:56,057: got traj at 1453718456057538032
[rosout][INFO] 2016-01-25 11:40:59,045: executing rest of traj at 1453718459045916080
[rosout][INFO] 2016-01-25 11:41:04,851: Time taken for rest of trajectory: 5.805413008
[rosout][INFO] 2016-01-25 11:41:19,907: got traj at 1453718479907946109
[rosout][INFO] 2016-01-25 11:41:22,902: executing rest of traj at 1453718482902435064
[rosout][INFO] 2016-01-25 11:41:28,711: Time taken for rest of trajectory: 5.808472872
[rosout][INFO] 2016-01-25 11:41:53,706: got traj at 1453718513706181049
[rosout][INFO] 2016-01-25 11:41:56,701: executing rest of traj at 1453718516701145887
[rosout][INFO] 2016-01-25 11:42:02,511: Time taken for rest of trajectory: 5.810150861
[rosout][INFO] 2016-01-25 11:42:17,108: got traj at 1453718537108661890
[rosout][INFO] 2016-01-25 11:42:20,103: executing rest of traj at 1453718540103095054
[rosout][INFO] 2016-01-25 11:42:25,912: Time taken for rest of trajectory: 5.808710813
[rosout][INFO] 2016-01-25 11:42:48,546: got traj at 1453718568546771049
[rosout][INFO] 2016-01-25 11:42:51,525: executing rest of traj at 1453718571525577068
[rosout][INFO] 2016-01-25 11:42:57,370: Time taken for rest of trajectory: 5.844207048
[rosout][INFO] 2016-01-25 11:43:14,880: got traj at 1453718594880886077
[rosout][INFO] 2016-01-25 11:43:17,855: executing rest of traj at 1453718597855552911
[rosout][INFO] 2016-01-25 11:43:23,664: Time taken for rest of trajectory: 5.808016061
[rosout][INFO] 2016-01-25 11:43:46,558: got traj at 1453718626558528900
[rosout][INFO] 2016-01-25 11:43:49,551: executing rest of traj at 1453718629551930904
[rosout][INFO] 2016-01-25 11:43:55,349: Time taken for rest of trajectory: 5.797272921
[rosout][INFO] 2016-01-25 11:44:08,966: got traj at 1453718648966732025
[rosout][INFO] 2016-01-25 11:44:11,963: executing rest of traj at 1453718651963484048
[rosout][INFO] 2016-01-25 11:44:18,047: Time taken for rest of trajectory: 6.083601952
[rosout][INFO] 2016-01-25 11:44:46,425: got traj at 1453718686424992084
[rosout][INFO] 2016-01-25 11:44:49,393: executing rest of traj at 1453718689393171072
[rosout][INFO] 2016-01-25 11:44:55,367: Time taken for rest of trajectory: 5.973923922
[rosout][INFO] 2016-01-25 11:45:10,644: got traj at 1453718710644439935
[rosout][INFO] 2016-01-25 11:45:13,587: executing rest of traj at 1453718713587472915
[rosout][INFO] 2016-01-25 11:45:21,387: Time taken for rest of trajectory: 7.799182176
[rosout][INFO] 2016-01-25 11:45:52,498: got traj at 1453718752498069047
[rosout][INFO] 2016-01-25 11:45:55,492: executing rest of traj at 1453718755492197990
[rosout][INFO] 2016-01-25 11:46:03,323: Time taken for rest of trajectory: 7.831257105
[rosout][INFO] 2016-01-25 11:46:21,594: got traj at 1453718781594223976
[rosout][INFO] 2016-01-25 11:46:24,583: executing rest of traj at 1453718784582907915
[rosout][INFO] 2016-01-25 11:46:32,387: Time taken for rest of trajectory: 7.803814888
[rosout][INFO] 2016-01-25 11:47:10,275: got traj at 1453718830275564908
[rosout][INFO] 2016-01-25 11:47:12,863: executing rest of traj at 1453718832863539934
[rosout][INFO] 2016-01-25 11:47:20,668: Time taken for rest of trajectory: 7.804726839
[rospy.internal][ERROR] 2016-01-25 11:47:29,735: Unable to initiate TCP/IP socket to 10.0.0.11:42647 (http://10.0.0.11:44466/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-25 11:47:30,744: Unknown error initiating TCP/IP socket to 10.0.0.11:42647 (http://10.0.0.11:44466/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-25 11:47:30,744: topic[/write_traj_downsampled] removing connection to http://10.0.0.11:44466/
[rospy.internal][WARNING] 2016-01-25 11:48:10,866: Unknown error initiating TCP/IP socket to 10.0.0.11:48009 (http://10.0.0.11:39218/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:10,866: topic[/tf] removing connection to http://10.0.0.11:39218/
[rospy.internal][WARNING] 2016-01-25 11:48:10,951: Unknown error initiating TCP/IP socket to 10.0.0.11:49053 (http://10.0.0.11:57999/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:10,951: topic[/tf] removing connection to http://10.0.0.11:57999/
[rospy.internal][WARNING] 2016-01-25 11:48:10,952: Unknown error initiating TCP/IP socket to 10.0.0.11:49025 (http://10.0.0.11:48801/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:10,952: topic[/tf] removing connection to http://10.0.0.11:48801/
[rospy.internal][WARNING] 2016-01-25 11:48:11,054: Unknown error initiating TCP/IP socket to 10.0.0.11:46904 (http://10.0.0.11:40819/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2016-01-25 11:48:11,055: Unknown error initiating TCP/IP socket to 10.0.0.11:57458 (http://10.0.0.11:32873/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:11,055: topic[/tf] removing connection to http://10.0.0.11:40819/
[rospy.internal][INFO] 2016-01-25 11:48:11,055: topic[/tf] removing connection to http://10.0.0.11:32873/
[rospy.internal][WARNING] 2016-01-25 11:48:11,055: Unknown error initiating TCP/IP socket to 10.0.0.11:39587 (http://10.0.0.11:33737/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:11,055: topic[/tf] removing connection to http://10.0.0.11:33737/
[rospy.internal][WARNING] 2016-01-25 11:48:11,055: Unknown error initiating TCP/IP socket to 10.0.0.11:56688 (http://10.0.0.11:57831/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:11,056: topic[/tf] removing connection to http://10.0.0.11:57831/
[rospy.internal][WARNING] 2016-01-25 11:48:11,346: Unknown error initiating TCP/IP socket to 10.0.0.11:43886 (http://10.0.0.11:56038/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 11:48:11,347: topic[/tf] removing connection to http://10.0.0.11:56038/
[rospy.core][INFO] 2016-01-25 12:34:08,963: signal_shutdown [signal-2]
[rospy.internal][WARNING] 2016-01-25 12:34:08,977: Unknown error initiating TCP/IP socket to 10.0.0.11:42632 (http://10.0.0.11:41840/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-25 12:34:08,977: topic[/tf] removing connection to http://10.0.0.11:41840/
[rospy.internal][INFO] 2016-01-25 12:34:08,979: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-25 12:34:08,980: topic[/tf] removing connection to http://10.0.0.11:49439/
[rospy.impl.masterslave][INFO] 2016-01-25 12:34:08,980: signal-2
[rospy.core][INFO] 2016-01-25 12:34:09,600: signal_shutdown [atexit]
