[rospy.client][INFO] 2016-01-28 08:51:41,268: init_node, name[/log], pid[17538]
[xmlrpc][INFO] 2016-01-28 08:51:41,275: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-28 08:51:41,276: ROS Slave URI: [http://10.0.0.11:50933/]
[xmlrpc][INFO] 2016-01-28 08:51:41,276: Started XML-RPC server [http://10.0.0.11:50933/]
[rospy.impl.masterslave][INFO] 2016-01-28 08:51:41,276: _ready: http://10.0.0.11:50933/
[xmlrpc][INFO] 2016-01-28 08:51:41,281: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 08:51:41,281: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 08:51:41,281: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,303: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,321: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,329: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,349: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,365: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,379: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,393: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,404: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,409: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,423: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,433: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,453: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,473: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,492: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,508: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:51:41,524: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 08:51:41,576: registered with master
[rospy.rosout][INFO] 2016-01-28 08:51:41,577: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 08:51:41,594: connected to core topic /rosout
[rospy.internal][INFO] 2016-01-28 08:51:41,602: topic[/time_response] adding connection to [http://10.0.0.3:37713/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:41,611: topic[/time_writing] adding connection to [http://10.0.0.3:37713/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:41,612: topic[/user_feedback] adding connection to [http://10.0.0.3:37713/], count 0
[rospy.simtime][INFO] 2016-01-28 08:51:41,612: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 08:51:41,624: topic[/clear_screen] adding connection to [http://10.0.0.3:37713/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:41,698: topic[/words_to_write] adding connection to [http://10.0.0.4:53811/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:41,764: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 08:51:42,789: topic[/activity] adding connection to [http://10.0.0.11:52306/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,153: topic[/clear_screen] adding connection to [http://10.0.0.11:36411/], count 1
[rospy.internal][INFO] 2016-01-28 08:51:43,168: topic[/current_demo] adding connection to [http://10.0.0.11:36411/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,169: topic[/current_learn] adding connection to [http://10.0.0.11:36411/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,173: topic[/nb_repetitions] adding connection to [http://10.0.0.11:36411/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,181: topic[/current_score] adding connection to [http://10.0.0.11:36411/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,187: topic[/clear_screen] adding connection to [http://10.0.0.11:37169/], count 2
[rospy.internal][INFO] 2016-01-28 08:51:43,201: topic[/activity] adding connection to [http://10.0.0.11:37169/], count 1
[rospy.internal][WARNING] 2016-01-28 08:54:21,826: Unknown error initiating TCP/IP socket to 10.0.0.3:46255 (http://10.0.0.3:37713/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 08:54:21,826: topic[/time_writing] removing connection to http://10.0.0.3:37713/
[rospy.internal][WARNING] 2016-01-28 08:54:21,835: Unknown error initiating TCP/IP socket to 10.0.0.3:46255 (http://10.0.0.3:37713/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 08:54:21,835: topic[/time_response] removing connection to http://10.0.0.3:37713/
[rospy.internal][WARNING] 2016-01-28 08:54:21,945: Unknown error initiating TCP/IP socket to 10.0.0.3:46255 (http://10.0.0.3:37713/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 08:54:21,945: topic[/clear_screen] removing connection to http://10.0.0.3:37713/
[rospy.internal][WARNING] 2016-01-28 08:54:21,966: Unknown error initiating TCP/IP socket to 10.0.0.3:46255 (http://10.0.0.3:37713/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 08:54:21,966: topic[/user_feedback] removing connection to http://10.0.0.3:37713/
[rospy.internal][INFO] 2016-01-28 08:54:26,519: topic[/clear_screen] adding connection to [http://10.0.0.3:46184/], count 2
[rospy.internal][INFO] 2016-01-28 08:54:26,576: topic[/user_feedback] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:54:26,578: topic[/time_writing] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:54:26,588: topic[/time_response] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:54:35,848: topic[/words_to_write] adding connection to [http://10.0.0.11:39365/], count 1
[rospy.internal][WARNING] 2016-01-28 08:54:38,774: Unknown error initiating TCP/IP socket to 10.0.0.11:46128 (http://10.0.0.11:39365/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-28 08:54:38,774: topic[/words_to_write] removing connection to http://10.0.0.11:39365/
[rospy.internal][INFO] 2016-01-28 08:54:50,816: topic[/words_to_write] adding connection to [http://10.0.0.11:39947/], count 1
[rospy.internal][WARNING] 2016-01-28 08:54:53,727: Unknown error initiating TCP/IP socket to 10.0.0.11:57579 (http://10.0.0.11:39947/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-28 08:54:53,727: topic[/words_to_write] removing connection to http://10.0.0.11:39947/
[rospy.internal][INFO] 2016-01-28 08:55:33,654: topic[/stop_learning] adding connection to [http://10.0.0.11:34771/], count 0
[rospy.internal][ERROR] 2016-01-28 08:55:34,193: Unable to initiate TCP/IP socket to 10.0.0.11:47139 (http://10.0.0.11:37169/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:34,196: Unable to initiate TCP/IP socket to 10.0.0.11:47139 (http://10.0.0.11:37169/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:34,999: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:35,000: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:35,002: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:35,002: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 08:55:35,003: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 08:55:35,194: Unknown error initiating TCP/IP socket to 10.0.0.11:47139 (http://10.0.0.11:37169/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:35,194: topic[/clear_screen] removing connection to http://10.0.0.11:37169/
[rospy.internal][WARNING] 2016-01-28 08:55:35,198: Unknown error initiating TCP/IP socket to 10.0.0.11:47139 (http://10.0.0.11:37169/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:35,198: topic[/activity] removing connection to http://10.0.0.11:37169/
[rospy.internal][WARNING] 2016-01-28 08:55:36,001: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:36,001: topic[/current_score] removing connection to http://10.0.0.11:36411/
[rospy.internal][WARNING] 2016-01-28 08:55:36,002: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:36,002: topic[/clear_screen] removing connection to http://10.0.0.11:36411/
[rospy.internal][WARNING] 2016-01-28 08:55:36,003: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:36,004: topic[/nb_repetitions] removing connection to http://10.0.0.11:36411/
[rospy.internal][WARNING] 2016-01-28 08:55:36,004: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2016-01-28 08:55:36,004: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:36,004: topic[/current_learn] removing connection to http://10.0.0.11:36411/
[rospy.internal][INFO] 2016-01-28 08:55:36,004: topic[/current_demo] removing connection to http://10.0.0.11:36411/
[rospy.internal][ERROR] 2016-01-28 08:55:36,622: Unable to initiate TCP/IP socket to 10.0.0.11:40026 (http://10.0.0.11:34771/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 08:55:37,623: Unknown error initiating TCP/IP socket to 10.0.0.11:40026 (http://10.0.0.11:34771/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:37,623: topic[/stop_learning] removing connection to http://10.0.0.11:34771/
[rospy.internal][ERROR] 2016-01-28 08:55:38,492: Unable to initiate TCP/IP socket to 10.0.0.11:41346 (http://10.0.0.11:52306/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 08:55:39,496: Unknown error initiating TCP/IP socket to 10.0.0.11:41346 (http://10.0.0.11:52306/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:39,496: topic[/activity] removing connection to http://10.0.0.11:52306/
[rospy.core][INFO] 2016-01-28 08:55:43,780: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 08:55:43,851: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 08:55:43,851: topic[/words_to_write] removing connection to http://10.0.0.4:53811/
[rospy.internal][INFO] 2016-01-28 08:55:43,852: topic[/clear_screen] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 08:55:43,852: topic[/user_feedback] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 08:55:43,852: topic[/time_writing] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 08:55:43,852: topic[/time_response] removing connection to http://10.0.0.3:46184/
[rospy.impl.masterslave][INFO] 2016-01-28 08:55:43,852: signal-2
[rospy.core][INFO] 2016-01-28 08:55:44,417: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-28 08:55:51,164: init_node, name[/log], pid[24249]
[xmlrpc][INFO] 2016-01-28 08:55:51,167: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 08:55:51,168: Started XML-RPC server [http://10.0.0.11:44161/]
[rospy.impl.masterslave][INFO] 2016-01-28 08:55:51,171: _ready: http://10.0.0.11:44161/
[xmlrpc][INFO] 2016-01-28 08:55:51,175: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 08:55:51,176: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 08:55:51,176: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 08:55:51,176: ROS Slave URI: [http://10.0.0.11:44161/]
[rospy.registration][INFO] 2016-01-28 08:55:51,189: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,196: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,208: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,212: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,260: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,284: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,304: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,315: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,326: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,336: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,342: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,354: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,358: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,368: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,380: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 08:55:51,389: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 08:55:51,495: registered with master
[rospy.rosout][INFO] 2016-01-28 08:55:51,496: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 08:55:51,513: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 08:55:51,527: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 08:55:51,556: topic[/time_writing] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:51,557: topic[/user_feedback] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:51,559: topic[/words_to_write] adding connection to [http://10.0.0.4:53811/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:51,560: topic[/time_response] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:51,569: topic[/clear_screen] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:51,739: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 08:55:52,648: topic[/activity] adding connection to [http://10.0.0.11:47728/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:52,660: topic[/current_score] adding connection to [http://10.0.0.11:32952/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:52,700: topic[/current_learn] adding connection to [http://10.0.0.11:32952/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:52,708: topic[/current_demo] adding connection to [http://10.0.0.11:32952/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:52,716: topic[/clear_screen] adding connection to [http://10.0.0.11:32952/], count 1
[rospy.internal][INFO] 2016-01-28 08:55:52,723: topic[/nb_repetitions] adding connection to [http://10.0.0.11:32952/], count 0
[rospy.internal][INFO] 2016-01-28 08:55:53,004: topic[/activity] adding connection to [http://10.0.0.11:57330/], count 1
[rospy.internal][INFO] 2016-01-28 08:55:53,005: topic[/clear_screen] adding connection to [http://10.0.0.11:57330/], count 2
[rospy.internal][INFO] 2016-01-28 08:56:10,225: topic[/words_to_write] adding connection to [http://10.0.0.11:48505/], count 1
[rospy.internal][ERROR] 2016-01-28 08:56:13,142: Unable to initiate TCP/IP socket to 10.0.0.11:44532 (http://10.0.0.11:48505/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 08:56:14,144: Unknown error initiating TCP/IP socket to 10.0.0.11:44532 (http://10.0.0.11:48505/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:56:14,144: topic[/words_to_write] removing connection to http://10.0.0.11:48505/
[rospy.internal][INFO] 2016-01-28 09:17:02,183: topic[/stop_learning] adding connection to [http://10.0.0.11:53217/], count 0
[rospy.internal][ERROR] 2016-01-28 09:17:02,791: Unable to initiate TCP/IP socket to 10.0.0.11:52105 (http://10.0.0.11:57330/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:02,794: Unable to initiate TCP/IP socket to 10.0.0.11:52105 (http://10.0.0.11:57330/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:03,759: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:03,763: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:03,764: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:03,765: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:17:03,765: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:17:03,817: Unknown error initiating TCP/IP socket to 10.0.0.11:52105 (http://10.0.0.11:57330/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:03,818: topic[/clear_screen] removing connection to http://10.0.0.11:57330/
[rospy.internal][WARNING] 2016-01-28 09:17:03,818: Unknown error initiating TCP/IP socket to 10.0.0.11:52105 (http://10.0.0.11:57330/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:03,818: topic[/activity] removing connection to http://10.0.0.11:57330/
[rospy.internal][WARNING] 2016-01-28 09:17:04,776: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,776: topic[/current_demo] removing connection to http://10.0.0.11:32952/
[rospy.internal][WARNING] 2016-01-28 09:17:04,776: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,776: topic[/nb_repetitions] removing connection to http://10.0.0.11:32952/
[rospy.internal][WARNING] 2016-01-28 09:17:04,776: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,777: topic[/clear_screen] removing connection to http://10.0.0.11:32952/
[rospy.internal][WARNING] 2016-01-28 09:17:04,777: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,777: topic[/current_score] removing connection to http://10.0.0.11:32952/
[rospy.internal][WARNING] 2016-01-28 09:17:04,778: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,778: topic[/current_learn] removing connection to http://10.0.0.11:32952/
[rospy.internal][WARNING] 2016-01-28 09:17:05,061: Unknown error initiating TCP/IP socket to 10.0.0.11:58307 (http://10.0.0.11:53217/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:05,061: topic[/stop_learning] removing connection to http://10.0.0.11:53217/
[rospy.internal][ERROR] 2016-01-28 09:17:08,232: Unable to initiate TCP/IP socket to 10.0.0.11:45557 (http://10.0.0.11:47728/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:17:09,257: Unknown error initiating TCP/IP socket to 10.0.0.11:45557 (http://10.0.0.11:47728/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:09,257: topic[/activity] removing connection to http://10.0.0.11:47728/
[rospy.core][INFO] 2016-01-28 09:17:16,347: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 09:17:16,405: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 09:17:16,405: topic[/words_to_write] removing connection to http://10.0.0.4:53811/
[rospy.internal][INFO] 2016-01-28 09:17:16,406: topic[/clear_screen] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:17:16,406: topic[/user_feedback] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:17:16,406: topic[/time_writing] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:17:16,407: topic[/time_response] removing connection to http://10.0.0.3:46184/
[rospy.impl.masterslave][INFO] 2016-01-28 09:17:16,407: signal-2
[rospy.internal][WARNING] 2016-01-28 09:17:16,457: Unknown error initiating TCP/IP socket to 10.0.0.4:42251 (http://10.0.0.4:53811/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2016-01-28 09:17:16,459: Unknown error initiating TCP/IP socket to 10.0.0.3:50038 (http://10.0.0.3:46184/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2016-01-28 09:17:16,460: Unknown error initiating TCP/IP socket to 10.0.0.3:50038 (http://10.0.0.3:46184/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2016-01-28 09:17:17,056: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-28 09:25:00,891: init_node, name[/log], pid[1377]
[xmlrpc][INFO] 2016-01-28 09:25:00,899: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 09:25:00,899: Started XML-RPC server [http://10.0.0.11:41317/]
[rospy.impl.masterslave][INFO] 2016-01-28 09:25:00,899: _ready: http://10.0.0.11:41317/
[rospy.init][INFO] 2016-01-28 09:25:00,899: ROS Slave URI: [http://10.0.0.11:41317/]
[xmlrpc][INFO] 2016-01-28 09:25:00,907: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 09:25:00,907: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 09:25:00,908: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 09:25:00,921: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 09:25:00,936: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 09:25:00,950: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 09:25:00,960: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 09:25:00,981: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,029: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,063: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,080: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,102: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,140: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,159: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,165: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,171: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,177: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,200: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 09:25:01,235: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 09:25:01,300: registered with master
[rospy.rosout][INFO] 2016-01-28 09:25:01,300: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 09:25:01,345: connected to core topic /rosout
[rospy.internal][INFO] 2016-01-28 09:25:01,357: topic[/words_to_write] adding connection to [http://10.0.0.4:44833/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:01,380: topic[/time_response] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:01,381: topic[/time_writing] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:01,382: topic[/clear_screen] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:01,382: topic[/user_feedback] adding connection to [http://10.0.0.3:46184/], count 0
[rospy.simtime][INFO] 2016-01-28 09:25:01,388: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 09:25:01,587: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 09:25:01,803: topic[/activity] adding connection to [http://10.0.0.11:57362/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,016: topic[/activity] adding connection to [http://10.0.0.11:43539/], count 1
[rospy.internal][INFO] 2016-01-28 09:25:02,021: topic[/clear_screen] adding connection to [http://10.0.0.11:43539/], count 1
[rospy.internal][INFO] 2016-01-28 09:25:02,387: topic[/current_score] adding connection to [http://10.0.0.11:57954/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,388: topic[/current_learn] adding connection to [http://10.0.0.11:57954/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,389: topic[/current_demo] adding connection to [http://10.0.0.11:57954/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,390: topic[/nb_repetitions] adding connection to [http://10.0.0.11:57954/], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,397: topic[/clear_screen] adding connection to [http://10.0.0.11:57954/], count 2
[rospy.internal][INFO] 2016-01-28 09:38:34,820: topic[/stop_learning] adding connection to [http://10.0.0.11:45834/], count 0
[rospy.internal][ERROR] 2016-01-28 09:38:35,957: Unable to initiate TCP/IP socket to 10.0.0.11:59304 (http://10.0.0.11:43539/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:35,961: Unable to initiate TCP/IP socket to 10.0.0.11:59304 (http://10.0.0.11:43539/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:36,030: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:36,033: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:36,034: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:36,036: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 09:38:36,036: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:38:36,976: Unknown error initiating TCP/IP socket to 10.0.0.11:59304 (http://10.0.0.11:43539/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:36,976: topic[/clear_screen] removing connection to http://10.0.0.11:43539/
[rospy.internal][WARNING] 2016-01-28 09:38:36,976: Unknown error initiating TCP/IP socket to 10.0.0.11:59304 (http://10.0.0.11:43539/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:36,977: topic[/activity] removing connection to http://10.0.0.11:43539/
[rospy.internal][WARNING] 2016-01-28 09:38:37,036: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,036: topic[/current_score] removing connection to http://10.0.0.11:57954/
[rospy.internal][WARNING] 2016-01-28 09:38:37,037: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,037: topic[/clear_screen] removing connection to http://10.0.0.11:57954/
[rospy.internal][WARNING] 2016-01-28 09:38:37,038: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,038: topic[/nb_repetitions] removing connection to http://10.0.0.11:57954/
[rospy.internal][WARNING] 2016-01-28 09:38:37,038: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,039: topic[/current_demo] removing connection to http://10.0.0.11:57954/
[rospy.internal][WARNING] 2016-01-28 09:38:37,039: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,039: topic[/current_learn] removing connection to http://10.0.0.11:57954/
[rospy.internal][ERROR] 2016-01-28 09:38:37,839: Unable to initiate TCP/IP socket to 10.0.0.11:36167 (http://10.0.0.11:45834/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:38:38,856: Unknown error initiating TCP/IP socket to 10.0.0.11:36167 (http://10.0.0.11:45834/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:38,856: topic[/stop_learning] removing connection to http://10.0.0.11:45834/
[rospy.internal][ERROR] 2016-01-28 09:38:40,910: Unable to initiate TCP/IP socket to 10.0.0.11:60648 (http://10.0.0.11:57362/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:38:41,911: Unknown error initiating TCP/IP socket to 10.0.0.11:60648 (http://10.0.0.11:57362/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:41,912: topic[/activity] removing connection to http://10.0.0.11:57362/
[rospy.core][INFO] 2016-01-28 09:39:23,664: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 09:39:23,685: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 09:39:23,686: topic[/words_to_write] removing connection to http://10.0.0.4:44833/
[rospy.internal][INFO] 2016-01-28 09:39:23,686: topic[/clear_screen] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:39:23,686: topic[/user_feedback] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:39:23,686: topic[/time_writing] removing connection to http://10.0.0.3:46184/
[rospy.internal][INFO] 2016-01-28 09:39:23,686: topic[/time_response] removing connection to http://10.0.0.3:46184/
[rospy.impl.masterslave][INFO] 2016-01-28 09:39:23,687: signal-2
[rospy.core][INFO] 2016-01-28 09:39:24,296: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-28 10:26:17,734: init_node, name[/log], pid[28441]
[xmlrpc][INFO] 2016-01-28 10:26:17,743: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-28 10:26:17,743: ROS Slave URI: [http://10.0.0.11:59676/]
[xmlrpc][INFO] 2016-01-28 10:26:17,743: Started XML-RPC server [http://10.0.0.11:59676/]
[rospy.impl.masterslave][INFO] 2016-01-28 10:26:17,744: _ready: http://10.0.0.11:59676/
[rospy.registration][INFO] 2016-01-28 10:26:17,767: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 10:26:17,768: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[xmlrpc][INFO] 2016-01-28 10:26:17,768: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 10:26:17,791: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,820: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,824: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,844: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,856: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,862: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,881: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,884: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,893: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,904: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,924: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,931: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,945: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,950: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,961: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 10:26:17,972: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 10:26:18,044: registered with master
[rospy.rosout][INFO] 2016-01-28 10:26:18,044: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 10:26:18,066: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 10:26:18,080: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 10:26:18,172: topic[/time_response] adding connection to [http://10.0.0.3:39241/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,188: topic[/clear_screen] adding connection to [http://10.0.0.3:39241/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,189: topic[/time_writing] adding connection to [http://10.0.0.3:39241/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,220: topic[/words_to_write] adding connection to [http://10.0.0.4:38119/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,332: topic[/user_feedback] adding connection to [http://10.0.0.3:39241/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,368: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 10:26:18,905: topic[/activity] adding connection to [http://10.0.0.11:53827/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,724: topic[/current_score] adding connection to [http://10.0.0.11:47373/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,724: topic[/current_demo] adding connection to [http://10.0.0.11:47373/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,726: topic[/clear_screen] adding connection to [http://10.0.0.11:47373/], count 1
[rospy.internal][INFO] 2016-01-28 10:26:19,726: topic[/current_learn] adding connection to [http://10.0.0.11:47373/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,727: topic[/nb_repetitions] adding connection to [http://10.0.0.11:47373/], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,840: topic[/activity] adding connection to [http://10.0.0.11:37486/], count 1
[rospy.internal][INFO] 2016-01-28 10:26:19,849: topic[/clear_screen] adding connection to [http://10.0.0.11:37486/], count 2
[rospy.internal][INFO] 2016-01-28 10:51:16,825: topic[/stop_learning] adding connection to [http://10.0.0.11:60278/], count 0
[rospy.internal][ERROR] 2016-01-28 10:51:17,669: Unable to initiate TCP/IP socket to 10.0.0.11:44237 (http://10.0.0.11:37486/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:17,670: Unable to initiate TCP/IP socket to 10.0.0.11:44237 (http://10.0.0.11:37486/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:18,381: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:18,383: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:18,384: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:18,384: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 10:51:18,385: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 10:51:18,676: Unknown error initiating TCP/IP socket to 10.0.0.11:44237 (http://10.0.0.11:37486/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:18,676: topic[/clear_screen] removing connection to http://10.0.0.11:37486/
[rospy.internal][WARNING] 2016-01-28 10:51:18,677: Unknown error initiating TCP/IP socket to 10.0.0.11:44237 (http://10.0.0.11:37486/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:18,677: topic[/activity] removing connection to http://10.0.0.11:37486/
[rospy.internal][WARNING] 2016-01-28 10:51:19,396: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,397: topic[/current_score] removing connection to http://10.0.0.11:47373/
[rospy.internal][WARNING] 2016-01-28 10:51:19,397: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,397: topic[/clear_screen] removing connection to http://10.0.0.11:47373/
[rospy.internal][WARNING] 2016-01-28 10:51:19,397: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,398: topic[/nb_repetitions] removing connection to http://10.0.0.11:47373/
[rospy.internal][WARNING] 2016-01-28 10:51:19,398: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,398: topic[/current_demo] removing connection to http://10.0.0.11:47373/
[rospy.internal][WARNING] 2016-01-28 10:51:19,397: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,399: topic[/current_learn] removing connection to http://10.0.0.11:47373/
[rospy.internal][ERROR] 2016-01-28 10:51:19,780: Unable to initiate TCP/IP socket to 10.0.0.11:41982 (http://10.0.0.11:60278/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 10:51:20,781: Unknown error initiating TCP/IP socket to 10.0.0.11:41982 (http://10.0.0.11:60278/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:20,781: topic[/stop_learning] removing connection to http://10.0.0.11:60278/
[rospy.internal][ERROR] 2016-01-28 10:51:21,765: Unable to initiate TCP/IP socket to 10.0.0.11:43547 (http://10.0.0.11:53827/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 10:51:22,776: Unknown error initiating TCP/IP socket to 10.0.0.11:43547 (http://10.0.0.11:53827/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:22,776: topic[/activity] removing connection to http://10.0.0.11:53827/
[rospy.core][INFO] 2016-01-28 10:54:58,902: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 10:54:58,918: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 10:54:58,918: topic[/words_to_write] removing connection to http://10.0.0.4:38119/
[rospy.internal][INFO] 2016-01-28 10:54:58,919: topic[/clear_screen] removing connection to http://10.0.0.3:39241/
[rospy.internal][INFO] 2016-01-28 10:54:58,919: topic[/user_feedback] removing connection to http://10.0.0.3:39241/
[rospy.internal][INFO] 2016-01-28 10:54:58,920: topic[/time_writing] removing connection to http://10.0.0.3:39241/
[rospy.internal][INFO] 2016-01-28 10:54:58,920: topic[/time_response] removing connection to http://10.0.0.3:39241/
[rospy.impl.masterslave][INFO] 2016-01-28 10:54:58,920: signal-2
[rospy.internal][WARNING] 2016-01-28 10:54:59,000: Unknown error initiating TCP/IP socket to 10.0.0.3:35230 (http://10.0.0.3:39241/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2016-01-28 10:54:59,535: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-28 11:06:23,052: init_node, name[/log], pid[12023]
[xmlrpc][INFO] 2016-01-28 11:06:23,060: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 11:06:23,060: Started XML-RPC server [http://10.0.0.11:50786/]
[rospy.impl.masterslave][INFO] 2016-01-28 11:06:23,060: _ready: http://10.0.0.11:50786/
[rospy.init][INFO] 2016-01-28 11:06:23,062: ROS Slave URI: [http://10.0.0.11:50786/]
[rospy.registration][INFO] 2016-01-28 11:06:23,079: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 11:06:23,080: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[xmlrpc][INFO] 2016-01-28 11:06:23,081: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 11:06:23,098: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,107: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,124: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,149: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,175: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,197: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,213: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,240: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,278: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,326: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,364: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,386: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,416: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,435: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,453: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 11:06:23,470: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 11:06:23,563: registered with master
[rospy.rosout][INFO] 2016-01-28 11:06:23,563: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 11:06:23,584: connected to core topic /rosout
[rospy.internal][INFO] 2016-01-28 11:06:23,591: topic[/words_to_write] adding connection to [http://10.0.0.4:56157/], count 0
[rospy.simtime][INFO] 2016-01-28 11:06:23,601: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 11:06:23,781: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 11:06:24,180: topic[/activity] adding connection to [http://10.0.0.11:50782/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,295: topic[/current_learn] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,296: topic[/current_score] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,300: topic[/current_demo] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,300: topic[/nb_repetitions] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,303: topic[/clear_screen] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,918: topic[/activity] adding connection to [http://10.0.0.11:34705/], count 1
[rospy.internal][INFO] 2016-01-28 11:06:25,925: topic[/clear_screen] adding connection to [http://10.0.0.11:34705/], count 1
[rospy.internal][INFO] 2016-01-28 11:06:30,212: topic[/clear_screen] adding connection to [http://10.0.0.3:43929/], count 2
[rospy.internal][INFO] 2016-01-28 11:06:30,303: topic[/time_writing] adding connection to [http://10.0.0.3:43929/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:30,306: topic[/time_response] adding connection to [http://10.0.0.3:43929/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:30,337: topic[/user_feedback] adding connection to [http://10.0.0.3:43929/], count 0
[rospy.internal][INFO] 2016-01-28 11:17:41,962: topic[/words_to_write] adding connection to [http://10.0.0.11:37217/], count 1
[rospy.internal][ERROR] 2016-01-28 11:17:45,039: Unable to initiate TCP/IP socket to 10.0.0.11:37586 (http://10.0.0.11:37217/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 11:17:46,056: Unknown error initiating TCP/IP socket to 10.0.0.11:37586 (http://10.0.0.11:37217/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:17:46,056: topic[/words_to_write] removing connection to http://10.0.0.11:37217/
[rospy.internal][INFO] 2016-01-28 11:39:29,120: topic[/stop_learning] adding connection to [http://10.0.0.11:59745/], count 0
[rospy.internal][ERROR] 2016-01-28 11:39:29,843: Unable to initiate TCP/IP socket to 10.0.0.11:36328 (http://10.0.0.11:34705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:29,847: Unable to initiate TCP/IP socket to 10.0.0.11:36328 (http://10.0.0.11:34705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:30,588: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:30,589: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:30,590: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:30,591: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 11:39:30,617: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 11:39:30,856: Unknown error initiating TCP/IP socket to 10.0.0.11:36328 (http://10.0.0.11:34705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:30,856: topic[/clear_screen] removing connection to http://10.0.0.11:34705/
[rospy.internal][WARNING] 2016-01-28 11:39:30,858: Unknown error initiating TCP/IP socket to 10.0.0.11:36328 (http://10.0.0.11:34705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:30,858: topic[/activity] removing connection to http://10.0.0.11:34705/
[rospy.internal][WARNING] 2016-01-28 11:39:31,589: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,589: topic[/current_score] removing connection to http://10.0.0.11:36145/
[rospy.internal][WARNING] 2016-01-28 11:39:31,590: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,590: topic[/clear_screen] removing connection to http://10.0.0.11:36145/
[rospy.internal][WARNING] 2016-01-28 11:39:31,592: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,592: topic[/nb_repetitions] removing connection to http://10.0.0.11:36145/
[rospy.internal][WARNING] 2016-01-28 11:39:31,592: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,592: topic[/current_demo] removing connection to http://10.0.0.11:36145/
[rospy.internal][WARNING] 2016-01-28 11:39:31,636: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,636: topic[/current_learn] removing connection to http://10.0.0.11:36145/
[rospy.internal][WARNING] 2016-01-28 11:39:32,140: Unknown error initiating TCP/IP socket to 10.0.0.11:40998 (http://10.0.0.11:59745/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-28 11:39:32,140: topic[/stop_learning] removing connection to http://10.0.0.11:59745/
[rospy.internal][ERROR] 2016-01-28 11:39:35,006: Unable to initiate TCP/IP socket to 10.0.0.11:36344 (http://10.0.0.11:50782/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 11:39:36,016: Unknown error initiating TCP/IP socket to 10.0.0.11:36344 (http://10.0.0.11:50782/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:36,017: topic[/activity] removing connection to http://10.0.0.11:50782/
[rospy.core][INFO] 2016-01-28 11:42:05,600: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 11:42:05,611: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 11:42:05,611: topic[/words_to_write] removing connection to http://10.0.0.4:56157/
[rospy.internal][INFO] 2016-01-28 11:42:05,612: topic[/clear_screen] removing connection to http://10.0.0.3:43929/
[rospy.internal][INFO] 2016-01-28 11:42:05,612: topic[/user_feedback] removing connection to http://10.0.0.3:43929/
[rospy.internal][INFO] 2016-01-28 11:42:05,613: topic[/time_writing] removing connection to http://10.0.0.3:43929/
[rospy.internal][INFO] 2016-01-28 11:42:05,613: topic[/time_response] removing connection to http://10.0.0.3:43929/
[rospy.impl.masterslave][INFO] 2016-01-28 11:42:05,613: signal-2
[rospy.internal][WARNING] 2016-01-28 11:42:05,676: Unknown error initiating TCP/IP socket to 10.0.0.3:44827 (http://10.0.0.3:43929/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2016-01-28 11:42:05,677: Unknown error initiating TCP/IP socket to 10.0.0.3:44827 (http://10.0.0.3:43929/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2016-01-28 11:42:05,678: Unknown error initiating TCP/IP socket to 10.0.0.3:44827 (http://10.0.0.3:43929/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2016-01-28 11:42:05,788: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-28 13:49:23,997: init_node, name[/log], pid[10597]
[xmlrpc][INFO] 2016-01-28 13:49:23,997: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-28 13:49:23,998: ROS Slave URI: [http://10.0.0.11:56346/]
[xmlrpc][INFO] 2016-01-28 13:49:23,998: Started XML-RPC server [http://10.0.0.11:56346/]
[rospy.impl.masterslave][INFO] 2016-01-28 13:49:23,998: _ready: http://10.0.0.11:56346/
[xmlrpc][INFO] 2016-01-28 13:49:24,007: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 13:49:24,008: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 13:49:24,008: registering subscriber topic [/words_to_write] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,009: registering subscriber topic [/novelty] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,021: registering subscriber topic [/activity] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,042: registering subscriber topic [/current_score] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,064: registering subscriber topic [/current_learn] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,084: registering subscriber topic [/sizeHead] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,113: registering subscriber topic [/clear_screen] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,152: registering subscriber topic [/nb_repetitions] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,189: registering subscriber topic [/lookAt] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,208: registering subscriber topic [/user_feedback] type [std_msgs/String] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,229: registering subscriber topic [/time_writing] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,265: registering subscriber topic [/current_demo] type [letter_learning_interaction/Shape] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,304: registering subscriber topic [/time_response] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,349: registering subscriber topic [/movement] type [std_msgs/Int16] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,384: registering subscriber topic [/smile] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,412: registering subscriber topic [/stop_learning] type [std_msgs/Empty] with master
[rospy.registration][INFO] 2016-01-28 13:49:24,434: registering subscriber topic [/new_child] type [std_msgs/String] with master
[rospy.init][INFO] 2016-01-28 13:49:24,498: registered with master
[rospy.rosout][INFO] 2016-01-28 13:49:24,499: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 13:49:24,512: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 13:49:24,521: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 13:49:24,529: topic[/time_response] adding connection to [http://10.0.0.3:56143/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,549: topic[/clear_screen] adding connection to [http://10.0.0.3:56143/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,550: topic[/user_feedback] adding connection to [http://10.0.0.3:56143/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,551: topic[/time_writing] adding connection to [http://10.0.0.3:56143/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,638: topic[/words_to_write] adding connection to [http://10.0.0.4:43766/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,751: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 13:49:24,993: topic[/activity] adding connection to [http://10.0.0.11:54289/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:25,411: topic[/clear_screen] adding connection to [http://10.0.0.11:57222/], count 1
[rospy.internal][INFO] 2016-01-28 13:49:25,420: topic[/current_score] adding connection to [http://10.0.0.11:55614/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:25,422: topic[/current_learn] adding connection to [http://10.0.0.11:55614/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:25,423: topic[/clear_screen] adding connection to [http://10.0.0.11:55614/], count 2
[rospy.internal][INFO] 2016-01-28 13:49:25,425: topic[/current_demo] adding connection to [http://10.0.0.11:55614/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:25,428: topic[/activity] adding connection to [http://10.0.0.11:57222/], count 1
[rospy.internal][INFO] 2016-01-28 13:49:25,437: topic[/nb_repetitions] adding connection to [http://10.0.0.11:55614/], count 0
[rospy.internal][WARNING] 2016-01-28 14:11:52,090: Unknown error initiating TCP/IP socket to 10.0.0.4:52850 (http://10.0.0.4:43766/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 14:11:52,090: topic[/words_to_write] removing connection to http://10.0.0.4:43766/
[rospy.internal][INFO] 2016-01-28 14:11:56,296: topic[/words_to_write] adding connection to [http://10.0.0.4:44821/], count 0
[rospy.internal][INFO] 2016-01-28 14:14:47,070: topic[/stop_learning] adding connection to [http://10.0.0.11:38956/], count 0
[rospy.internal][ERROR] 2016-01-28 14:14:47,845: Unable to initiate TCP/IP socket to 10.0.0.11:48676 (http://10.0.0.11:57222/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 14:14:47,848: Unable to initiate TCP/IP socket to 10.0.0.11:48676 (http://10.0.0.11:57222/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 14:14:48,857: Unknown error initiating TCP/IP socket to 10.0.0.11:48676 (http://10.0.0.11:57222/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:48,857: topic[/clear_screen] removing connection to http://10.0.0.11:57222/
[rospy.internal][WARNING] 2016-01-28 14:14:48,858: Unknown error initiating TCP/IP socket to 10.0.0.11:48676 (http://10.0.0.11:57222/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:48,858: topic[/activity] removing connection to http://10.0.0.11:57222/
[rospy.internal][ERROR] 2016-01-28 14:14:48,869: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 14:14:48,869: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 14:14:48,870: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 14:14:48,870: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-01-28 14:14:48,871: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 14:14:49,876: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,876: topic[/nb_repetitions] removing connection to http://10.0.0.11:55614/
[rospy.internal][WARNING] 2016-01-28 14:14:49,876: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,876: topic[/current_learn] removing connection to http://10.0.0.11:55614/
[rospy.internal][WARNING] 2016-01-28 14:14:49,876: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,876: topic[/current_demo] removing connection to http://10.0.0.11:55614/
[rospy.internal][WARNING] 2016-01-28 14:14:49,877: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,877: topic[/clear_screen] removing connection to http://10.0.0.11:55614/
[rospy.internal][WARNING] 2016-01-28 14:14:49,876: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,880: topic[/current_score] removing connection to http://10.0.0.11:55614/
[rospy.internal][WARNING] 2016-01-28 14:14:50,140: Unknown error initiating TCP/IP socket to 10.0.0.11:60882 (http://10.0.0.11:38956/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-28 14:14:50,140: topic[/stop_learning] removing connection to http://10.0.0.11:38956/
[rospy.internal][ERROR] 2016-01-28 14:14:52,170: Unable to initiate TCP/IP socket to 10.0.0.11:33882 (http://10.0.0.11:54289/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 14:14:53,176: Unknown error initiating TCP/IP socket to 10.0.0.11:33882 (http://10.0.0.11:54289/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:53,176: topic[/activity] removing connection to http://10.0.0.11:54289/
[rospy.core][INFO] 2016-01-28 14:29:02,641: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 14:29:02,662: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 14:29:02,663: topic[/words_to_write] removing connection to http://10.0.0.4:44821/
[rospy.internal][INFO] 2016-01-28 14:29:02,663: topic[/clear_screen] removing connection to http://10.0.0.3:56143/
[rospy.internal][INFO] 2016-01-28 14:29:02,664: topic[/user_feedback] removing connection to http://10.0.0.3:56143/
[rospy.internal][INFO] 2016-01-28 14:29:02,664: topic[/time_writing] removing connection to http://10.0.0.3:56143/
[rospy.internal][INFO] 2016-01-28 14:29:02,664: topic[/time_response] removing connection to http://10.0.0.3:56143/
[rospy.impl.masterslave][INFO] 2016-01-28 14:29:02,664: signal-2
[rospy.core][INFO] 2016-01-28 14:29:02,772: signal_shutdown [atexit]
