[rospy.client][INFO] 2016-01-28 08:51:31,175: init_node, name[/withmeness], pid[17257]
[xmlrpc][INFO] 2016-01-28 08:51:31,175: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 08:51:31,176: Started XML-RPC server [http://10.0.0.11:49451/]
[rospy.init][INFO] 2016-01-28 08:51:31,176: ROS Slave URI: [http://10.0.0.11:49451/]
[rospy.impl.masterslave][INFO] 2016-01-28 08:51:31,176: _ready: http://10.0.0.11:49451/
[xmlrpc][INFO] 2016-01-28 08:51:31,176: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 08:51:31,176: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 08:51:31,177: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-28 08:51:31,191: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-28 08:51:31,276: registered with master
[rospy.rosout][INFO] 2016-01-28 08:51:31,276: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 08:51:31,278: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 08:51:31,279: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 08:51:31,293: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:40566/], count 0
[rospy.internal][INFO] 2016-01-28 08:51:31,521: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 08:51:43,213: topic[/state_activity] adding connection to [http://10.0.0.11:36411/], count 0
[rospy.internal][ERROR] 2016-01-28 08:55:34,999: Unable to initiate TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 08:55:36,000: Unknown error initiating TCP/IP socket to 10.0.0.11:46672 (http://10.0.0.11:36411/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 08:55:36,000: topic[/state_activity] removing connection to http://10.0.0.11:36411/
[rospy.internal][INFO] 2016-01-28 08:55:52,627: topic[/state_activity] adding connection to [http://10.0.0.11:32952/], count 0
[rospy.internal][ERROR] 2016-01-28 09:17:03,758: Unable to initiate TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:17:04,776: Unknown error initiating TCP/IP socket to 10.0.0.11:60973 (http://10.0.0.11:32952/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:17:04,776: topic[/state_activity] removing connection to http://10.0.0.11:32952/
[rospy.core][INFO] 2016-01-28 09:17:20,592: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 09:17:20,596: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-28 09:17:20,597: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 09:17:20,598: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:40566/
[rospy.impl.masterslave][INFO] 2016-01-28 09:17:20,598: signal-2
[rospy.internal][WARNING] 2016-01-28 09:17:20,689: Unknown error initiating TCP/IP socket to 10.0.0.11:50715 (http://10.0.0.11:40566/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.core][INFO] 2016-01-28 09:17:35,643: signal_shutdown [signal-15]
[rospy.client][INFO] 2016-01-28 09:24:55,501: init_node, name[/withmeness], pid[1057]
[xmlrpc][INFO] 2016-01-28 09:24:55,501: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 09:24:55,501: Started XML-RPC server [http://10.0.0.11:50624/]
[rospy.init][INFO] 2016-01-28 09:24:55,502: ROS Slave URI: [http://10.0.0.11:50624/]
[rospy.impl.masterslave][INFO] 2016-01-28 09:24:55,502: _ready: http://10.0.0.11:50624/
[rospy.registration][INFO] 2016-01-28 09:24:55,502: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-28 09:24:55,502: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 09:24:55,502: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-28 09:24:55,546: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-28 09:24:55,602: registered with master
[rospy.rosout][INFO] 2016-01-28 09:24:55,602: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 09:24:55,604: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 09:24:55,605: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 09:24:55,618: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:54707/], count 0
[rospy.internal][INFO] 2016-01-28 09:24:55,861: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 09:25:02,389: topic[/state_activity] adding connection to [http://10.0.0.11:57954/], count 0
[rospy.internal][ERROR] 2016-01-28 09:38:36,031: Unable to initiate TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 09:38:37,036: Unknown error initiating TCP/IP socket to 10.0.0.11:40828 (http://10.0.0.11:57954/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 09:38:37,037: topic[/state_activity] removing connection to http://10.0.0.11:57954/
[rospy.core][INFO] 2016-01-28 09:39:26,862: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 09:39:26,867: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-28 09:39:26,867: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 09:39:26,867: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:54707/
[rospy.impl.masterslave][INFO] 2016-01-28 09:39:26,868: signal-2
[rospy.core][INFO] 2016-01-28 09:39:41,871: signal_shutdown [signal-15]
[rospy.client][INFO] 2016-01-28 10:25:31,660: init_node, name[/withmeness], pid[28104]
[xmlrpc][INFO] 2016-01-28 10:25:31,660: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 10:25:31,661: Started XML-RPC server [http://10.0.0.11:36127/]
[rospy.init][INFO] 2016-01-28 10:25:31,661: ROS Slave URI: [http://10.0.0.11:36127/]
[rospy.impl.masterslave][INFO] 2016-01-28 10:25:31,661: _ready: http://10.0.0.11:36127/
[rospy.registration][INFO] 2016-01-28 10:25:31,662: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-28 10:25:31,662: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 10:25:31,662: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-28 10:25:31,687: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-28 10:25:31,761: registered with master
[rospy.rosout][INFO] 2016-01-28 10:25:31,761: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 10:25:31,763: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 10:25:31,764: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 10:25:31,779: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:53220/], count 0
[rospy.internal][INFO] 2016-01-28 10:25:31,983: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 10:26:19,705: topic[/state_activity] adding connection to [http://10.0.0.11:47373/], count 0
[rospy.internal][ERROR] 2016-01-28 10:51:18,381: Unable to initiate TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 10:51:19,396: Unknown error initiating TCP/IP socket to 10.0.0.11:38700 (http://10.0.0.11:47373/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 10:51:19,396: topic[/state_activity] removing connection to http://10.0.0.11:47373/
[rospy.core][INFO] 2016-01-28 10:54:54,628: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 10:54:54,631: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-28 10:54:54,632: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 10:54:54,632: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:53220/
[rospy.impl.masterslave][INFO] 2016-01-28 10:54:54,632: signal-2
[rospy.core][INFO] 2016-01-28 10:55:09,713: signal_shutdown [signal-15]
[rospy.client][INFO] 2016-01-28 11:06:17,885: init_node, name[/withmeness], pid[11741]
[xmlrpc][INFO] 2016-01-28 11:06:17,885: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 11:06:17,885: Started XML-RPC server [http://10.0.0.11:53135/]
[rospy.init][INFO] 2016-01-28 11:06:17,886: ROS Slave URI: [http://10.0.0.11:53135/]
[rospy.impl.masterslave][INFO] 2016-01-28 11:06:17,886: _ready: http://10.0.0.11:53135/
[xmlrpc][INFO] 2016-01-28 11:06:17,886: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 11:06:17,886: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 11:06:17,887: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-28 11:06:17,917: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-28 11:06:17,986: registered with master
[rospy.rosout][INFO] 2016-01-28 11:06:17,986: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 11:06:17,988: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 11:06:17,989: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 11:06:18,003: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:56317/], count 0
[rospy.internal][INFO] 2016-01-28 11:06:18,257: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 11:06:25,329: topic[/state_activity] adding connection to [http://10.0.0.11:36145/], count 0
[rospy.internal][ERROR] 2016-01-28 11:39:30,587: Unable to initiate TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 11:39:31,587: Unknown error initiating TCP/IP socket to 10.0.0.11:55427 (http://10.0.0.11:36145/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 11:39:31,588: topic[/state_activity] removing connection to http://10.0.0.11:36145/
[rospy.core][INFO] 2016-01-28 11:42:06,920: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 11:42:06,926: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-28 11:42:06,926: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 11:42:06,926: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:56317/
[rospy.impl.masterslave][INFO] 2016-01-28 11:42:06,926: signal-2
[rospy.core][INFO] 2016-01-28 11:42:21,985: signal_shutdown [signal-15]
[rospy.client][INFO] 2016-01-28 13:49:13,071: init_node, name[/withmeness], pid[10322]
[xmlrpc][INFO] 2016-01-28 13:49:13,071: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-28 13:49:13,072: Started XML-RPC server [http://10.0.0.11:48469/]
[rospy.init][INFO] 2016-01-28 13:49:13,072: ROS Slave URI: [http://10.0.0.11:48469/]
[rospy.impl.masterslave][INFO] 2016-01-28 13:49:13,072: _ready: http://10.0.0.11:48469/
[xmlrpc][INFO] 2016-01-28 13:49:13,073: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-28 13:49:13,073: Registering with master node http://10.0.0.11:11311/
[rospy.registration][INFO] 2016-01-28 13:49:13,074: Registering publisher topic [/withmeness_topic] type [std_msgs/Float64] with master
[rospy.internal][INFO] 2016-01-28 13:49:13,096: topic[/withmeness_topic] adding connection to [/attention_log], count 0
[rospy.init][INFO] 2016-01-28 13:49:13,172: registered with master
[rospy.rosout][INFO] 2016-01-28 13:49:13,173: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-28 13:49:13,174: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-28 13:49:13,175: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-28 13:49:13,190: topic[/actual_focus_of_attention] adding connection to [http://10.0.0.11:56108/], count 0
[rospy.internal][INFO] 2016-01-28 13:49:13,450: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-28 13:49:25,424: topic[/state_activity] adding connection to [http://10.0.0.11:55614/], count 0
[rospy.internal][ERROR] 2016-01-28 14:14:48,867: Unable to initiate TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-28 14:14:49,879: Unknown error initiating TCP/IP socket to 10.0.0.11:44855 (http://10.0.0.11:55614/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-28 14:14:49,879: topic[/state_activity] removing connection to http://10.0.0.11:55614/
[rospy.core][INFO] 2016-01-28 14:14:55,161: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-28 14:14:55,169: topic[/withmeness_topic] removing connection to /attention_log
[rospy.internal][INFO] 2016-01-28 14:14:55,170: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-28 14:14:55,171: topic[/actual_focus_of_attention] removing connection to http://10.0.0.11:56108/
[rospy.impl.masterslave][INFO] 2016-01-28 14:14:55,172: signal-2
[rospy.internal][WARNING] 2016-01-28 14:14:55,546: Unknown error initiating TCP/IP socket to 10.0.0.11:37494 (http://10.0.0.11:56108/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2016-01-28 14:15:10,198: signal_shutdown [signal-15]
